// AUTO-GENERATED by scripts/sync-modules.js (auto-discovering)
// DO NOT EDIT MANUALLY
// Source of truth: ABA-variants/WABA

export const wabaModules = {
    core: {
        "base": `%% WABA Base Logic (Semiring/Monoid-Independent) - GROUNDING OPTIMIZED
%% This file contains the core argumentation logic that is independent
%% of the choice of semiring (weight propagation) and monoid (cost aggregation).
%%
%% OPTIMIZATIONS APPLIED:
%% - Added unary domain predicates to reduce grounding size
%% - Use rule/1 consistently instead of head(R,_)
%% - Removed redundant supported(X) joins

%% Budget constant used by the supported CLI wrapper and by raw clingo runs.
%% Framework files may also state budget(beta); duplicate identical facts are harmless.

%% ====================
%% DOMAIN PREDICATES
%% ====================
%% These unary predicates reduce grounding by avoiding repeated existential patterns

%% Rule meta-predicate (R is a rule identifier)
rule(R) :- head(R,_).

%% Unary flag: X appears as some rule head
is_head(X) :- head(_,X).

%% Unary flag: R has at least one body element
has_body(R) :- body(R,_).

%% Derived atoms: heads that are not assumptions
derived_atom(X) :- is_head(X), not assumption(X).

%% ====================
%% CORE LOGIC
%% ====================

%% Support computation (weight-independent)
%% An atom is supported if:
%% 1. It's an assumption that is in, OR
%% 2. There exists a rule with this atom as head and all body elements are supported
supported(X) :- assumption(X), in(X).
supported(X) :- head(R,X), triggered_by_in(R).

%% A rule is triggered when all its body elements are supported
%% OPTIMIZED: Use rule(R) instead of head(R,_) for domain
triggered_by_in(R) :- rule(R), supported(X) : body(R,X).

%% Attack computation
%% An attack exists when a supported atom X attacks an assumption Y
%% (where Y's contrary is X), with the weight of X
%% OPTIMIZED: Remove redundant supported(X) check (supported_with_weight(X,W) implies support)
attacks_with_weight(X,Y,W) :- supported_with_weight(X,W), assumption(Y), contrary(Y,X).

%% Attack discretion choice
%% We can choose to discard any attack (at a cost)
{ discarded_attack(X,Y,W) : attacks_with_weight(X,Y,W) }.

%% Successful attacks
%% An attack succeeds if it's not discarded
attacks_successfully_with_weight(X,Y,W) :- attacks_with_weight(X,Y,W), not discarded_attack(X,Y,W).

%% ====================
%% BUDGET CONSTRAINT
%% ====================
%% Budget Constraints
%% ====================
%%
%% Budget value is typically set via command line: -c beta=N
budget(beta).

%% Budget constraints are in constraint/ directory.
%% \`constraint/ub.lp\` and \`constraint/lb.lp\` read the aggregate family from
%% the loaded monoid module.
%%
%% Load appropriate constraint file for budget enforcement:
%% - constraint/ub.lp - Upper bound for the active monoid family (cost ≤ beta)
%% - constraint/lb.lp - Lower bound for the active monoid family (cost ≥ beta)
%% - constraint/no_discard.lp - Plain ABA mode (no attack discarding)
`
    },
    semiring: {
        "arctic": `%% Arctic (Max-Plus) Semiring for Weight Propagation
%% Semiring: (ℤ ∪ {±∞}, max, +, #inf, 0)
%% - Domain: ℤ ∪ {±∞} (integers plus positive/negative infinity)
%% - Disjunction/⊕ (OR): max (strongest alternative)
%% - Conjunction/⊗ (AND): + (accumulate rewards)
%% - Additive identity: #inf (identity for max operation)
%% - Multiplicative identity: 0 (identity for + operation)
%% - Interpretation: weights are rewards/benefits, higher is better
%%
%% SEMANTICS: Reward Accumulation / Longest Path
%% ==============================================
%% The Arctic semiring is the DUAL of the Tropical semiring:
%% - Tropical: (+, min) for cost minimization / shortest path
%% - Arctic: (+, max) for reward maximization / longest path
%%
%% Key applications:
%% - Scoring arguments by accumulated support/evidence
%% - Finding strongest evidence chains (sum of supporting weights)
%% - Benefit/reward optimization (opposite of cost minimization)
%% - Longest path problems in graphs
%%
%% Comparison to Tropical:
%% - Tropical: weights are costs (lower is better), minimize sum
%% - Arctic: weights are rewards (higher is better), maximize sum
%%
%% Note: "Arctic" comes from tropical algebra (hot=min, cold=max)

active_semiring(arctic).
%% Default weight policy selection for unweighted assumptions.
%%
%% Semiring modules provide semiring_default_weight(policy, value).
%% Callers may optionally load one explicit policy module from defaults/.
%% If none is loaded, legacy behavior is preserved.

configured_default_policy :- explicit_default_policy(_).

:- explicit_default_policy(P1), explicit_default_policy(P2), P1 != P2.

active_default_policy(P) :- explicit_default_policy(P).
active_default_policy(legacy) :- not configured_default_policy.

default_assumption_weight(W) :-
    active_default_policy(P),
    semiring_default_weight(P, W).

:- active_default_policy(P), not semiring_default_weight(P, _).


semiring_default_weight(legacy,0).
semiring_default_weight(aba,#sup).
semiring_default_weight(neutral,0).

%% ========================================
%% DEFAULT WEIGHT PRINCIPLE: NEUTRALITY
%% ========================================
%%
%% Unweighted atoms receive the MULTIPLICATIVE IDENTITY (0):
%% - For addition: 0 + x = x (neutral, doesn't affect accumulation)
%% - Default weight of 0 means "no reward contributed"
%%
%% IMPORTANT: This differs from Tropical semiring!
%% - Tropical uses #sup as default (infinitely expensive to discard)
%% - Arctic uses 0 as default (neutral contribution, easily discarded)
%%
%% For Arctic semiring:
%% - Multiplicative identity = 0 (neutral for addition)
%% - Meaning: Unweighted assumptions contribute zero reward
%% - Discard cost with max monoid: max(0, ...) = other weights (not dominating)
%% - Discard cost with sum monoid: sum + 0 = sum (neutral)
%%
%% This creates different semantics than Tropical:
%% - Tropical: Unweighted assumptions are "hard to discard" (#sup)
%% - Arctic: Unweighted assumptions are "neutral" (0 reward)
%%
%% If you want unweighted assumptions to be "hard to discard" in Arctic,
%% the monoid should assign #sup as default (monoid/*.lp files handle this).

%% Assumptions with explicit weights
supported_with_weight(X,W) :- assumption(X), in(X), weight(X,W), not head(_,X).

%% Assumptions without explicit weights: Use multiplicative identity (0)
%% For Arctic semiring, unweighted assumptions get 0 (neutral reward)
%% Rationale: Neutral contribution to reward accumulation
%% - In conjunction (+): 0 + x = x (doesn't affect sum)
%% - In disjunction (max): max(0, x) = x for x > 0 (neutral for positive rewards)
%%
%% NOTE: This is the MULTIPLICATIVE identity (neutral for conjunction).
%% For "hard to discard" semantics, monoids assign #sup as default weight.
supported_with_weight(X,W) :- assumption(X), in(X), not weight(X,_), not head(_,X), default_assumption_weight(W).

%% Step 1: Compute weight for each rule derivation using conjunction (addition)
%% For rule R deriving X: sum weights of all body elements (accumulate rewards)
%% IMPORTANT: Only compute weight for TRIGGERED rules (all body elements supported)

%% Special handling for #sup and #inf: clingo's #sum aggregate has limitations
%% - #sum ignores #sup values (with warning)
%% - #inf is handled correctly
%% We detect infinite values before aggregation to preserve them

%% Helper: detect if any body element has #sup weight (infinite reward)
body_has_sup_weight(R) :- body(R,B), supported_with_weight(B,#sup).

%% Helper: detect if any body element has #inf weight (infinitely negative)
body_has_inf_weight(R) :- body(R,B), supported_with_weight(B,#inf).

%% If any body has #sup, derivation weight is #sup (infinite reward propagates)
rule_derivation_weight(R,X,#sup) :-
    head(R,X),
    supported(X),
    body(R,_),
    triggered_by_in(R),
    body_has_sup_weight(R).

%% If any body has #inf (and no #sup), derivation weight is #inf
rule_derivation_weight(R,X,#inf) :-
    head(R,X),
    supported(X),
    body(R,_),
    triggered_by_in(R),
    not body_has_sup_weight(R),
    body_has_inf_weight(R).

%% Otherwise, sum finite weights (standard case)
rule_derivation_weight(R,X,W) :-
    head(R,X),
    supported(X),
    body(R,_),
    triggered_by_in(R),
    not body_has_sup_weight(R),
    not body_has_inf_weight(R),
    W = #sum{ V,B : body(R,B), supported_with_weight(B,V) }.

%% Handle rules with empty bodies (facts): Use 0 (multiplicative identity for +)
%% An empty body is an empty CONJUNCTION, so it must equal the multiplicative (⊗)
%% identity = 0. This keeps the empty body TRANSPARENT in + (0+x=x); over the
%% supported (nonnegative) weight surface a standalone fact then carries 0 reward.
%%
%% (Earlier this used #inf, the ADDITIVE identity. #inf is dropped/absorbed by the
%% reward-accumulating +, so conclusions derived through a fact were corrupted.
%% Classical ABA recovery is preserved via constraint/no_discard.lp.)
rule_derivation_weight(R,X,0) :-
    head(R,X),
    supported(X),
    not body(R,_),
    not weight(X,_).  % weighted facts keep their explicit weight (override)

%% Step 2: Combine multiple derivations using disjunction (maximum)
%% The weight of X is the maximum across all its rule derivations
%% AND any explicit weight (OR semantics: explicit weight is another "derivation")
%% Interpretation: Multiple derivation paths → take strongest/highest reward path
supported_with_weight(X,W) :-
    supported(X),
    head(_,X),  % X is derived (not just an assumption)
    W = #max{ V : rule_derivation_weight(_,X,V) ;
              V : weight(X,V) }.

%% ========================================================================
%% UNDEFEATED WEIGHT COMPUTATION (for Budget-Aware Admissibility Defense)
%% ========================================================================

%% Base cases
undefeated_weight(X,W) :-
    assumption(X),
    not defeated(X),
    not weight(X,_),
    not head(_,X),
    default_assumption_weight(W).
undefeated_weight(X,W) :- assumption(X), not defeated(X), weight(X,W), not head(_,X).

%% Rule derivation with Arctic conjunction (addition)
undefeated_rule_weight(R,X,W) :-
    head(R,X),
    derived_from_undefeated(X),
    body(R,_),
    triggered_by_undefeated(R),
    W = #sum{ V,B : body(R,B), undefeated_weight(B,V) }.

%% Disjunction (max)
undefeated_weight(X,W) :-
    derived_from_undefeated(X),
    head(_,X),
    not assumption(X),
    W = #max{ V,R : undefeated_rule_weight(R,X,V) }.

%% NON-FLAT: Assumptions that are also rule heads
undefeated_weight(X,W) :-
    assumption(X),
    not defeated(X),
    derived_from_undefeated(X),
    head(_,X),
    weight(X,_),
    W = #max{ V,R : undefeated_rule_weight(R,X,V) ;
              V : weight(X,V) }.

undefeated_weight(X,W) :-
    assumption(X),
    not defeated(X),
    derived_from_undefeated(X),
    head(_,X),
    not weight(X,_),
    default_assumption_weight(D),
    W = #max{ V,R : undefeated_rule_weight(R,X,V) ;
              D : true }.

%% Polarity: Strength (higher is better)
%% Classical ABA: beta=#sup (can't meet threshold) or beta=0 (backward compatibility)
unaffordable_attack(W,B) :- undefeated_weight(_,W), budget(B), B = #sup, W != #sup.
unaffordable_attack(W,B) :- undefeated_weight(_,W), budget(B), B = 0, W != #inf.
unaffordable_attack(W,B) :- undefeated_weight(_,W), budget(B), B != #sup, B != 0, W < B.
`,
        "bottleneck_cost": `%% Bottleneck-Cost Semiring for Weight Propagation
%% Semiring: (ℤ ∪ {±∞}, min, max, #sup, #inf)
%% - Domain: ℤ ∪ {±∞} (integers plus positive/negative infinity)
%% - Disjunction/⊕ (OR): min (cheapest alternative)
%% - Conjunction/⊗ (AND): max (bottleneck / worst component)
%% - Additive identity: #sup (identity for min operation)
%% - Multiplicative identity: #inf (identity for max operation)
%% - Interpretation: weights are costs/penalties, LOWER is better
%%
%% SEMANTICS: Bottleneck Cost / Maximum Penalty
%% ============================================
%% The bottleneck-cost semiring models scenarios where:
%% - A chain's cost is determined by its WORST/highest-cost component (max for conjunction)
%% - Among alternatives, choose the CHEAPEST path (min for disjunction)
%% - Applications: Bottleneck problems, worst-case cost, maximum penalty
%%
%% Key insight: This is the DUAL of standard min/max bottleneck:
%% - Standard bottleneck (min/max): Maximize minimum capacity
%% - Bottleneck-cost (max/min): Minimize maximum cost
%%
%% Examples:
%% - Quality control: Reject batch if ANY component exceeds defect threshold (max)
%% - Security: System vulnerability = worst component vulnerability (max)
%% - Logistics: Route cost = bottleneck (slowest/most expensive segment)

active_semiring(bottleneck_cost).
%% Default weight policy selection for unweighted assumptions.
%%
%% Semiring modules provide semiring_default_weight(policy, value).
%% Callers may optionally load one explicit policy module from defaults/.
%% If none is loaded, legacy behavior is preserved.

configured_default_policy :- explicit_default_policy(_).

:- explicit_default_policy(P1), explicit_default_policy(P2), P1 != P2.

active_default_policy(P) :- explicit_default_policy(P).
active_default_policy(legacy) :- not configured_default_policy.

default_assumption_weight(W) :-
    active_default_policy(P),
    semiring_default_weight(P, W).

:- active_default_policy(P), not semiring_default_weight(P, _).


semiring_default_weight(legacy,#inf).
semiring_default_weight(aba,#sup).
semiring_default_weight(neutral,#inf).

%% =============================================
%% CLASSICAL ABA RECOVERY (No Discarding)
%% =============================================
%%
%% To recover plain unweighted ABA behavior with this semiring:
%%
%% UPPER BOUND REGIME (MAX, SUM, COUNT, LEX monoids):
%%   δ = #sup     (default weight for unweighted assumptions)
%%   β = 0        (budget value)
%%   Mechanism: constraint/ub.lp explicitly rejects discarding #sup-weighted attacks
%%
%% LOWER BOUND REGIME (MIN monoid):
%%   δ = #inf     (default weight for unweighted assumptions)
%%   β = 0        (budget value)
%%   Mechanism: MIN(#inf) = #inf < 0, rejected by constraint/lb.lp
%%   Alternative: δ = #sup with special constraint rejection
%%
%% CURRENT IMPLEMENTATION: δ = #sup (see line ~60 below)
%% This enables ABA recovery for UB monoids with β = 0.
%% For LB monoids, use δ = #inf by setting all assumption weights explicitly.
%%
%% Comparison to Tropical:
%% - Tropical (+/min): Minimize SUM of costs (total cost matters)
%% - Bottleneck-cost (max/min): Minimize MAX of costs (worst-case matters)

%% ========================================
%% DEFAULT WEIGHT PRINCIPLE: INFIMUM
%% ========================================
%%
%% Unweighted atoms receive the INFIMUM (minimum value in range):
%% - For bottleneck-cost semantics: #inf = infinitely GOOD (zero cost)
%% - Meaning: Unweighted assumptions impose no cost/penalty
%%
%% IMPORTANT: This differs from Tropical and Arctic!
%% - Tropical: #sup default (infinitely expensive, hard to discard)
%% - Bottleneck-cost: #inf default (zero cost, easy to discard)
%%
%% For Bottleneck-cost semiring:
%% - Multiplicative identity = #inf (neutral for max)
%% - Meaning: Unweighted assumptions contribute zero cost
%% - In conjunction (max): max(#inf, x) = x (no cost added)
%% - In disjunction (min): min(#inf, x) = #inf (infinitely cheap path)
%%
%% This creates "optimistic" semantics:
%% - Unweighted assumptions are assumed to be "free" (zero cost)
%% - Only explicit weights impose costs
%%
%% If you want unweighted assumptions to be "hard to discard", the monoid
%% should assign #sup as default weight (monoid/*.lp files handle this).

%% Assumptions with explicit weights
%% FLAT-WABA: assumption is not a rule head
%% NON-FLAT-WABA: if assumption is also a rule head, weight is computed below via rule derivation
supported_with_weight(X,W) :- assumption(X), in(X), weight(X,W), not head(_,X).

%% Assumptions without explicit weights: Use multiplicative identity (#inf)
%% For Bottleneck-cost semiring, unweighted assumptions get #inf (zero cost)
%% Rationale: Neutral contribution to bottleneck cost
%% - In conjunction (max): max(#inf, x) = x (doesn't affect bottleneck)
%% - In disjunction (min): min(#inf, x) = #inf (infinitely cheap)
%%
%% NOTE: This is the MULTIPLICATIVE identity (neutral for conjunction).
%% For "hard to discard" semantics, monoids assign #sup as default weight.
%%
%% FLAT-WABA: assumption is not a rule head
%% NON-FLAT-WABA: if assumption is also a rule head, weight is computed below via rule derivation
supported_with_weight(X,W) :-
    assumption(X),
    in(X),
    not weight(X,_),
    not head(_,X),
    default_assumption_weight(W).

%% Step 1: Compute weight for each rule derivation using conjunction (maximum)
%% For rule R deriving X: take MAXIMUM weight among all body elements (bottleneck)
%% Interpretation: Chain is only as good as its WORST (highest-cost) component
%% IMPORTANT: Only compute weight for TRIGGERED rules (all body elements supported)
rule_derivation_weight(R,X,W) :-
    head(R,X),
    supported(X),
    body(R,_),  % Only for rules with bodies
    triggered_by_in(R),  % Only triggered rules
    W = #max{ V,B : body(R,B), supported_with_weight(B,V) }.

%% Handle rules with empty bodies (facts): Use #inf (multiplicative identity for max)
%% An empty body is an empty CONJUNCTION, so it must equal the multiplicative (⊗)
%% identity = #inf. This keeps the empty body TRANSPARENT in max (max(#inf,x)=x), so a
%% fact used inside a longer rule body does not affect the bottleneck of the chain.
%%
%% (Earlier this used #sup, the ADDITIVE identity. But #sup is the max-ANNIHILATOR
%% (max(#sup,x)=#sup), so any conclusion derived through a fact collapsed to #sup,
%% poisoning every conjunctive chain through a fact. Classical ABA recovery is
%% preserved via constraint/no_discard.lp.)
rule_derivation_weight(R,X,#inf) :-
    head(R,X),
    supported(X),
    not body(R,_),
    not weight(X,_).  % weighted facts keep their explicit weight (override)

%% Step 2: Combine multiple derivations using disjunction (minimum)
%% IMPORTANT: Use DISJUNCTION OPERATOR (⊕) to combine weights from different paths:
%% - Multiple rule derivations are combined via ⊕
%% - Explicit weight is another "path" to support, combined via ⊕
%% - For Bottleneck-cost semiring: ⊕ = min (choose cheapest/lowest-cost path)
%%
%% SEMANTICS: Explicit weight + derived weight represent ALTERNATIVE support paths.
%% The actual weight is their DISJUNCTION, not conjunction or override.
%%
%% Example: If X has explicit weight 50 and is also derived with weight 30,
%%          then supported_with_weight(X, min(50, 30)) = supported_with_weight(X, 30)
%%          (the cheaper path is chosen)
supported_with_weight(X,W) :-
    supported(X),
    head(_,X),  % X is derived (not just an assumption)
    not assumption(X),  % X is not an assumption
    W = #min{ V,R : rule_derivation_weight(R,X,V) ;
              V : weight(X,V) }.  % DISJUNCTION (⊕ = min for Bottleneck-cost)

%% NON-FLAT-WABA: Derived assumption with explicit weight
%% Combine rule-derived weight with explicit weight via DISJUNCTION (min)
supported_with_weight(X,W) :-
    assumption(X),
    supported(X),
    head(_,X),  % Assumption is also derived
    weight(X,_),  % Has explicit weight
    W = #min{ V,R : rule_derivation_weight(R,X,V) ;
              V : weight(X,V) }.  % DISJUNCTION (⊕ = min for Bottleneck-cost)

%% NON-FLAT-WABA: Derived assumption WITHOUT explicit weight, but is IN
%% Combine rule-derived weight with default assumption weight (#inf) via DISJUNCTION (min)
supported_with_weight(X,W) :-
    assumption(X),
    in(X),  % Assumption is selected
    supported(X),
    head(_,X),  % Assumption is also derived
    not weight(X,_),  % No explicit weight
    default_assumption_weight(D),
    W = #min{ V,R : rule_derivation_weight(R,X,V) ;
              D : true }.  % Direct assumption path selected by the active default policy

%% ========================================================================
%% UNDEFEATED WEIGHT COMPUTATION (for Budget-Aware Admissibility Defense)
%% ========================================================================

%% Base cases
undefeated_weight(X,W) :-
    assumption(X),
    not defeated(X),
    not weight(X,_),
    not head(_,X),
    default_assumption_weight(W).
undefeated_weight(X,W) :- assumption(X), not defeated(X), weight(X,W), not head(_,X).

%% Rule derivation with Bottleneck conjunction (max - worst component)
undefeated_rule_weight(R,X,W) :-
    head(R,X),
    derived_from_undefeated(X),
    body(R,_),
    triggered_by_undefeated(R),
    W = #max{ V,B : body(R,B), undefeated_weight(B,V) }.

%% Disjunction (min - cheapest path)
undefeated_weight(X,W) :-
    derived_from_undefeated(X),
    head(_,X),
    not assumption(X),
    W = #min{ V,R : undefeated_rule_weight(R,X,V) }.

%% NON-FLAT: Assumptions that are also rule heads
undefeated_weight(X,W) :-
    assumption(X),
    not defeated(X),
    derived_from_undefeated(X),
    head(_,X),
    weight(X,_),
    W = #min{ V,R : undefeated_rule_weight(R,X,V) ;
              V : weight(X,V) }.

undefeated_weight(X,W) :-
    assumption(X),
    not defeated(X),
    derived_from_undefeated(X),
    head(_,X),
    not weight(X,_),
    default_assumption_weight(D),
    W = #min{ V,R : undefeated_rule_weight(R,X,V) ;
              D : true }.

%% Polarity: Cost (lower is better)
%% Special case: beta=0 means classical ABA (all attacks unaffordable)
unaffordable_attack(W,B) :- undefeated_weight(_,W), budget(B), B = 0, W != #inf.
unaffordable_attack(W,B) :- undefeated_weight(_,W), budget(B), B != 0, W > B.
`,
        "godel": `%% Gödel Semiring for Weight Propagation (Fuzzy Logic) - GROUNDING OPTIMIZED
%% Semiring: (ℤ ∪ {±∞}, max, min, #inf, #sup)
%% - Domain: All integers plus infinities
%% - Disjunction/⊕ (OR, multiple derivations): max (strongest alternative)
%% - Conjunction/⊗ (AND, body elements): min (weakest link)
%% - Additive identity: #inf (identity for max operation)
%% - Multiplicative identity: #sup (identity for min operation)
%% - Interpretation: weights are truth degrees, higher is better
%%
%% OPTIMIZATIONS APPLIED:
%% - Use not is_head(X) instead of not head(_,X)
%% - Use not has_body(R) instead of not body(R,_)
%% - Use rule(R) consistently for rule domains
%% - Remove redundant supported(X) checks
%%
%% In Gödel fuzzy logic:
%% - Domain: ℤ ∪ {±∞} (integers plus positive/negative infinity)
%% - Conjunction takes the minimum (weakest link in a chain)
%% - Disjunction takes the maximum (strongest of multiple proofs)
%% - Unweighted atoms get #sup (maximum truth, hardest to discard)

active_semiring(godel).
%% Default weight policy selection for unweighted assumptions.
%%
%% Semiring modules provide semiring_default_weight(policy, value).
%% Callers may optionally load one explicit policy module from defaults/.
%% If none is loaded, legacy behavior is preserved.

configured_default_policy :- explicit_default_policy(_).

:- explicit_default_policy(P1), explicit_default_policy(P2), P1 != P2.

active_default_policy(P) :- explicit_default_policy(P).
active_default_policy(legacy) :- not configured_default_policy.

default_assumption_weight(W) :-
    active_default_policy(P),
    semiring_default_weight(P, W).

:- active_default_policy(P), not semiring_default_weight(P, _).


semiring_default_weight(legacy,#sup).
semiring_default_weight(aba,#sup).
semiring_default_weight(neutral,#sup).

%% =============================================
%% CLASSICAL ABA RECOVERY (No Discarding)
%% =============================================
%%
%% To recover plain unweighted ABA behavior with this semiring:
%%
%% UPPER BOUND REGIME (MAX, SUM, COUNT, LEX monoids):
%%   δ = #sup     (default weight for unweighted assumptions)
%%   β = 0        (budget value)
%%   Mechanism: constraint/ub.lp explicitly rejects discarding #sup-weighted attacks
%%              (line 41: \`:- discarded_attack(_,_,#sup), budget(B), B != #sup.\`)
%%
%% LOWER BOUND REGIME (MIN monoid):
%%   Option 1 (recommended):
%%     δ = #inf   (default weight)
%%     β = 0      (budget value)
%%     Mechanism: MIN(#inf) = #inf < 0, rejected by constraint/lb.lp
%%   Option 2:
%%     δ = #sup   (default weight)
%%     β = any    (any finite budget)
%%     Mechanism: constraint/lb.lp explicitly rejects discarding #sup attacks
%%                (line 43: \`:- discarded_attack(_,_,#sup).\`)
%%
%% CURRENT IMPLEMENTATION: δ = #sup (see line ~45 below)
%% This enables ABA recovery for all monoids with appropriate budget settings.

%% ========================================
%% DEFAULT WEIGHT PRINCIPLE: SUPREMUM
%% ========================================
%%
%% Unweighted atoms receive the SUPREMUM (maximum value in range):
%% - Matches standard ABA: assumptions accepted by default ("innocent until proven guilty")
%% - "Hardest to discard": attacks from unweighted atoms are maximally expensive
%% - Budget semantics: requires budget ≥ #sup to discard such attacks
%%
%% For Gödel semiring:
%% - Supremum = #sup (positive infinity, fully true, maximum truth degree)
%% - Meaning: Unweighted assumptions have maximum truth value
%% - Discard cost with max monoid: max(#sup, ...) = #sup (infinitely expensive)
%% - Discard cost with min monoid: not compatible (see compatibility theory)
%% - Discard cost with sum monoid: sum += #sup → #sup (infinitely expensive)
%%
%% Explicit weights REPLACE the supremum default (via mutually exclusive rules).
%% DEFAULT WEIGHTS for unweighted atoms are now defined in monoid/*.lp files,
%% since the monoid determines what "hard to discard" means.
%%

%% Assumptions with explicit weights
%% FLAT-WABA: assumption is not a rule head
%% NON-FLAT-WABA: if assumption is also a rule head, weight is computed below via rule derivation
%% OPTIMIZED: Use not is_head(X) instead of not head(_,X)
supported_with_weight(X,W) :- assumption(X), in(X), weight(X,W), not is_head(X).

%% Assumptions without explicit weights: Use supremum (maximum truth value)
%% For Gödel semiring, unweighted assumptions get #sup (maximum truth degree)
%% Rationale: Unweighted assumptions are "hardest to discard" (default acceptance)
%% - Matches standard ABA semantics: assumptions accepted by default
%% - #sup = positive infinity (supremum, maximum value)
%% - In conjunction (min): min(#sup, x) = x (doesn't affect derivations)
%% - In disjunction (max): max(#sup, x) = #sup (dominates, represents maximum truth)
%%
%% NOTE: Uses #sup (positive infinity) as the supremum value.
%% Constraints must handle #sup specially for budget checking.
%%
%% FLAT-WABA: assumption is not a rule head
%% NON-FLAT-WABA: if assumption is also a rule head, weight is computed below via rule derivation
%% OPTIMIZED: Use not is_head(X) instead of not head(_,X)
supported_with_weight(X,W) :-
    assumption(X),
    in(X),
    not weight(X,_),
    not is_head(X),
    default_assumption_weight(W).

%% Step 1: Compute weight for each rule derivation using conjunction (minimum)
%% For rule R deriving X: take minimum weight among all body elements
%% IMPORTANT: Only compute weight for TRIGGERED rules (all body elements supported)
%% OPTIMIZED: Use rule(R) instead of head(R,X), remove redundant supported(X) check
rule_derivation_weight(R,X,W) :-
    rule(R),
    head(R,X),
    has_body(R),  % Only for rules with bodies
    triggered_by_in(R),  % Only triggered rules (prevents #sup from unsupported bodies)
    W = #min{ V,B : body(R,B), supported_with_weight(B,V) }.

%% Handle rules with empty bodies (facts): Use #sup (multiplicative identity for min).
%% An empty body is an empty CONJUNCTION, so it must equal the multiplicative (⊗)
%% identity = #sup. This makes the empty body TRANSPARENT in min (min(#sup,x)=x), so
%% an UNWEIGHTED fact is maximally certain and does not affect a longer chain.
%%
%% Guarded by \`not weight(X,_)\`: an explicitly weighted fact (e.g. \`risk(high) <- T\`
%% with weight(risk(high),7)) keeps its own weight. Without the guard, the ⊕ = max
%% combine below would let #sup dominate the explicit weight (max(#sup,7)=#sup),
%% silently discarding authored weights on facts.
%%
%% (Earlier this used #inf, the ADDITIVE identity and min-ANNIHILATOR (min(#inf,x)=#inf),
%% which poisoned every conjunctive chain through a fact.)
%%
%% OPTIMIZED: Use not has_body(R) instead of not body(R,_), use rule(R)
rule_derivation_weight(R,X,#sup) :-
    rule(R),
    head(R,X),
    not has_body(R),
    not weight(X,_).

%% Step 2: Combine multiple derivations using disjunction (maximum)
%% IMPORTANT: Use DISJUNCTION OPERATOR (⊕) to combine weights from different paths:
%% - Multiple rule derivations are combined via ⊕
%% - Explicit weight is another "path" to support, combined via ⊕
%% - For Gödel semiring: ⊕ = max (choose strongest/highest truth path)
%%
%% SEMANTICS: Explicit weight + derived weight represent ALTERNATIVE support paths.
%% The actual weight is their DISJUNCTION, not conjunction or override.
%%
%% Example: If X has explicit weight 50 and is also derived with weight 80,
%%          then supported_with_weight(X, max(50, 80)) = supported_with_weight(X, 80)
%%          (the stronger path is chosen)
%% OPTIMIZED: Use derived_atom(X) instead of head(_,X), not assumption(X)
supported_with_weight(X,W) :-
    derived_atom(X),
    supported(X),
    W = #max{ V,R : rule_derivation_weight(R,X,V) ;
              V : weight(X,V) }.  % DISJUNCTION (⊕ = max for Gödel)

%% NON-FLAT-WABA: Derived assumption with explicit weight
%% Combine rule-derived weight with explicit weight via DISJUNCTION (max)
%% OPTIMIZED: Use is_head(X) instead of head(_,X)
supported_with_weight(X,W) :-
    assumption(X),
    supported(X),
    is_head(X),  % Assumption is also derived
    weight(X,_),  % Has explicit weight
    W = #max{ V,R : rule_derivation_weight(R,X,V) ;
              V : weight(X,V) }.  % DISJUNCTION (⊕ = max for Gödel)

%% NON-FLAT-WABA: Derived assumption WITHOUT explicit weight, but is IN
%% For Gödel: max(derived, #sup) = #sup always (default dominates)
%% NOTE: Clingo ignores #sup in aggregates, so we assign it explicitly
%% OPTIMIZED: Use is_head(X) instead of head(_,X)
supported_with_weight(X,W) :-
    assumption(X),
    in(X),  % Assumption is selected
    supported(X),
    is_head(X),  % Assumption is also derived
    not weight(X,_),
    default_assumption_weight(W).

undefeated_weight(X,W) :- assumption(X), not defeated(X), default_assumption_weight(W).
undefeated_weight(X,W) :- derived_from_undefeated(X), weight(X,W).
undefeated_weight(X,W) :- derived_from_undefeated(X), head(R,X), W = #min{ V,B : body(R,B), undefeated_weight(B,V) }.
%% Polarity: Strength (higher is better)
%% Classical ABA: beta=#sup (can't meet threshold) or beta=0 (backward compatibility)
unaffordable_attack(W,B) :- undefeated_weight(_,W), budget(B), B = #sup, W != #sup.
unaffordable_attack(W,B) :- undefeated_weight(_,W), budget(B), B = 0, W != #inf.
unaffordable_attack(W,B) :- undefeated_weight(_,W), budget(B), B != #sup, B != 0, W < B.
`,
        "godel_low": `%% ALIAS — not a separate algebra.
%% \`godel_low\` is the lower-is-better (cost) polarity dual of \`godel\` (max,min).
%% That dual is exactly the (min, max) bottleneck-cost algebra, so this file is a
%% thin alias for semiring/bottleneck_cost.lp. Kept so that \`--semiring godel_low\`
%% and raw \`clingo ... semiring/godel_low.lp ...\` runs keep resolving.
%% Bottleneck-Cost Semiring for Weight Propagation
%% Semiring: (ℤ ∪ {±∞}, min, max, #sup, #inf)
%% - Domain: ℤ ∪ {±∞} (integers plus positive/negative infinity)
%% - Disjunction/⊕ (OR): min (cheapest alternative)
%% - Conjunction/⊗ (AND): max (bottleneck / worst component)
%% - Additive identity: #sup (identity for min operation)
%% - Multiplicative identity: #inf (identity for max operation)
%% - Interpretation: weights are costs/penalties, LOWER is better
%%
%% SEMANTICS: Bottleneck Cost / Maximum Penalty
%% ============================================
%% The bottleneck-cost semiring models scenarios where:
%% - A chain's cost is determined by its WORST/highest-cost component (max for conjunction)
%% - Among alternatives, choose the CHEAPEST path (min for disjunction)
%% - Applications: Bottleneck problems, worst-case cost, maximum penalty
%%
%% Key insight: This is the DUAL of standard min/max bottleneck:
%% - Standard bottleneck (min/max): Maximize minimum capacity
%% - Bottleneck-cost (max/min): Minimize maximum cost
%%
%% Examples:
%% - Quality control: Reject batch if ANY component exceeds defect threshold (max)
%% - Security: System vulnerability = worst component vulnerability (max)
%% - Logistics: Route cost = bottleneck (slowest/most expensive segment)

active_semiring(bottleneck_cost).
%% Default weight policy selection for unweighted assumptions.
%%
%% Semiring modules provide semiring_default_weight(policy, value).
%% Callers may optionally load one explicit policy module from defaults/.
%% If none is loaded, legacy behavior is preserved.

configured_default_policy :- explicit_default_policy(_).

:- explicit_default_policy(P1), explicit_default_policy(P2), P1 != P2.

active_default_policy(P) :- explicit_default_policy(P).
active_default_policy(legacy) :- not configured_default_policy.

default_assumption_weight(W) :-
    active_default_policy(P),
    semiring_default_weight(P, W).

:- active_default_policy(P), not semiring_default_weight(P, _).


semiring_default_weight(legacy,#inf).
semiring_default_weight(aba,#sup).
semiring_default_weight(neutral,#inf).

%% =============================================
%% CLASSICAL ABA RECOVERY (No Discarding)
%% =============================================
%%
%% To recover plain unweighted ABA behavior with this semiring:
%%
%% UPPER BOUND REGIME (MAX, SUM, COUNT, LEX monoids):
%%   δ = #sup     (default weight for unweighted assumptions)
%%   β = 0        (budget value)
%%   Mechanism: constraint/ub.lp explicitly rejects discarding #sup-weighted attacks
%%
%% LOWER BOUND REGIME (MIN monoid):
%%   δ = #inf     (default weight for unweighted assumptions)
%%   β = 0        (budget value)
%%   Mechanism: MIN(#inf) = #inf < 0, rejected by constraint/lb.lp
%%   Alternative: δ = #sup with special constraint rejection
%%
%% CURRENT IMPLEMENTATION: δ = #sup (see line ~60 below)
%% This enables ABA recovery for UB monoids with β = 0.
%% For LB monoids, use δ = #inf by setting all assumption weights explicitly.
%%
%% Comparison to Tropical:
%% - Tropical (+/min): Minimize SUM of costs (total cost matters)
%% - Bottleneck-cost (max/min): Minimize MAX of costs (worst-case matters)

%% ========================================
%% DEFAULT WEIGHT PRINCIPLE: INFIMUM
%% ========================================
%%
%% Unweighted atoms receive the INFIMUM (minimum value in range):
%% - For bottleneck-cost semantics: #inf = infinitely GOOD (zero cost)
%% - Meaning: Unweighted assumptions impose no cost/penalty
%%
%% IMPORTANT: This differs from Tropical and Arctic!
%% - Tropical: #sup default (infinitely expensive, hard to discard)
%% - Bottleneck-cost: #inf default (zero cost, easy to discard)
%%
%% For Bottleneck-cost semiring:
%% - Multiplicative identity = #inf (neutral for max)
%% - Meaning: Unweighted assumptions contribute zero cost
%% - In conjunction (max): max(#inf, x) = x (no cost added)
%% - In disjunction (min): min(#inf, x) = #inf (infinitely cheap path)
%%
%% This creates "optimistic" semantics:
%% - Unweighted assumptions are assumed to be "free" (zero cost)
%% - Only explicit weights impose costs
%%
%% If you want unweighted assumptions to be "hard to discard", the monoid
%% should assign #sup as default weight (monoid/*.lp files handle this).

%% Assumptions with explicit weights
%% FLAT-WABA: assumption is not a rule head
%% NON-FLAT-WABA: if assumption is also a rule head, weight is computed below via rule derivation
supported_with_weight(X,W) :- assumption(X), in(X), weight(X,W), not head(_,X).

%% Assumptions without explicit weights: Use multiplicative identity (#inf)
%% For Bottleneck-cost semiring, unweighted assumptions get #inf (zero cost)
%% Rationale: Neutral contribution to bottleneck cost
%% - In conjunction (max): max(#inf, x) = x (doesn't affect bottleneck)
%% - In disjunction (min): min(#inf, x) = #inf (infinitely cheap)
%%
%% NOTE: This is the MULTIPLICATIVE identity (neutral for conjunction).
%% For "hard to discard" semantics, monoids assign #sup as default weight.
%%
%% FLAT-WABA: assumption is not a rule head
%% NON-FLAT-WABA: if assumption is also a rule head, weight is computed below via rule derivation
supported_with_weight(X,W) :-
    assumption(X),
    in(X),
    not weight(X,_),
    not head(_,X),
    default_assumption_weight(W).

%% Step 1: Compute weight for each rule derivation using conjunction (maximum)
%% For rule R deriving X: take MAXIMUM weight among all body elements (bottleneck)
%% Interpretation: Chain is only as good as its WORST (highest-cost) component
%% IMPORTANT: Only compute weight for TRIGGERED rules (all body elements supported)
rule_derivation_weight(R,X,W) :-
    head(R,X),
    supported(X),
    body(R,_),  % Only for rules with bodies
    triggered_by_in(R),  % Only triggered rules
    W = #max{ V,B : body(R,B), supported_with_weight(B,V) }.

%% Handle rules with empty bodies (facts): Use #inf (multiplicative identity for max)
%% An empty body is an empty CONJUNCTION, so it must equal the multiplicative (⊗)
%% identity = #inf. This keeps the empty body TRANSPARENT in max (max(#inf,x)=x), so a
%% fact used inside a longer rule body does not affect the bottleneck of the chain.
%%
%% (Earlier this used #sup, the ADDITIVE identity. But #sup is the max-ANNIHILATOR
%% (max(#sup,x)=#sup), so any conclusion derived through a fact collapsed to #sup,
%% poisoning every conjunctive chain through a fact. Classical ABA recovery is
%% preserved via constraint/no_discard.lp.)
rule_derivation_weight(R,X,#inf) :-
    head(R,X),
    supported(X),
    not body(R,_),
    not weight(X,_).  % weighted facts keep their explicit weight (override)

%% Step 2: Combine multiple derivations using disjunction (minimum)
%% IMPORTANT: Use DISJUNCTION OPERATOR (⊕) to combine weights from different paths:
%% - Multiple rule derivations are combined via ⊕
%% - Explicit weight is another "path" to support, combined via ⊕
%% - For Bottleneck-cost semiring: ⊕ = min (choose cheapest/lowest-cost path)
%%
%% SEMANTICS: Explicit weight + derived weight represent ALTERNATIVE support paths.
%% The actual weight is their DISJUNCTION, not conjunction or override.
%%
%% Example: If X has explicit weight 50 and is also derived with weight 30,
%%          then supported_with_weight(X, min(50, 30)) = supported_with_weight(X, 30)
%%          (the cheaper path is chosen)
supported_with_weight(X,W) :-
    supported(X),
    head(_,X),  % X is derived (not just an assumption)
    not assumption(X),  % X is not an assumption
    W = #min{ V,R : rule_derivation_weight(R,X,V) ;
              V : weight(X,V) }.  % DISJUNCTION (⊕ = min for Bottleneck-cost)

%% NON-FLAT-WABA: Derived assumption with explicit weight
%% Combine rule-derived weight with explicit weight via DISJUNCTION (min)
supported_with_weight(X,W) :-
    assumption(X),
    supported(X),
    head(_,X),  % Assumption is also derived
    weight(X,_),  % Has explicit weight
    W = #min{ V,R : rule_derivation_weight(R,X,V) ;
              V : weight(X,V) }.  % DISJUNCTION (⊕ = min for Bottleneck-cost)

%% NON-FLAT-WABA: Derived assumption WITHOUT explicit weight, but is IN
%% Combine rule-derived weight with default assumption weight (#inf) via DISJUNCTION (min)
supported_with_weight(X,W) :-
    assumption(X),
    in(X),  % Assumption is selected
    supported(X),
    head(_,X),  % Assumption is also derived
    not weight(X,_),  % No explicit weight
    default_assumption_weight(D),
    W = #min{ V,R : rule_derivation_weight(R,X,V) ;
              D : true }.  % Direct assumption path selected by the active default policy

%% ========================================================================
%% UNDEFEATED WEIGHT COMPUTATION (for Budget-Aware Admissibility Defense)
%% ========================================================================

%% Base cases
undefeated_weight(X,W) :-
    assumption(X),
    not defeated(X),
    not weight(X,_),
    not head(_,X),
    default_assumption_weight(W).
undefeated_weight(X,W) :- assumption(X), not defeated(X), weight(X,W), not head(_,X).

%% Rule derivation with Bottleneck conjunction (max - worst component)
undefeated_rule_weight(R,X,W) :-
    head(R,X),
    derived_from_undefeated(X),
    body(R,_),
    triggered_by_undefeated(R),
    W = #max{ V,B : body(R,B), undefeated_weight(B,V) }.

%% Disjunction (min - cheapest path)
undefeated_weight(X,W) :-
    derived_from_undefeated(X),
    head(_,X),
    not assumption(X),
    W = #min{ V,R : undefeated_rule_weight(R,X,V) }.

%% NON-FLAT: Assumptions that are also rule heads
undefeated_weight(X,W) :-
    assumption(X),
    not defeated(X),
    derived_from_undefeated(X),
    head(_,X),
    weight(X,_),
    W = #min{ V,R : undefeated_rule_weight(R,X,V) ;
              V : weight(X,V) }.

undefeated_weight(X,W) :-
    assumption(X),
    not defeated(X),
    derived_from_undefeated(X),
    head(_,X),
    not weight(X,_),
    default_assumption_weight(D),
    W = #min{ V,R : undefeated_rule_weight(R,X,V) ;
              D : true }.

%% Polarity: Cost (lower is better)
%% Special case: beta=0 means classical ABA (all attacks unaffordable)
unaffordable_attack(W,B) :- undefeated_weight(_,W), budget(B), B = 0, W != #inf.
unaffordable_attack(W,B) :- undefeated_weight(_,W), budget(B), B != 0, W > B.

`,
        "tropical": `%% Tropical Semiring for Weight Propagation
%% Semiring: (ℤ ∪ {±∞}, min, +, #sup, 0)
%% - Domain: All integers plus infinities
%% - Disjunction/⊕ (OR, multiple derivations): min (choose best path)
%% - Conjunction/⊗ (AND, body elements): + (accumulate costs)
%% - Additive identity: #sup (identity for min operation)
%% - Multiplicative identity: 0 (identity for addition)
%% - Interpretation: weights are costs, lower is better
%%
%% This is the tropical semiring used for shortest path problems.

active_semiring(tropical).
%% Default weight policy selection for unweighted assumptions.
%%
%% Semiring modules provide semiring_default_weight(policy, value).
%% Callers may optionally load one explicit policy module from defaults/.
%% If none is loaded, legacy behavior is preserved.

configured_default_policy :- explicit_default_policy(_).

:- explicit_default_policy(P1), explicit_default_policy(P2), P1 != P2.

active_default_policy(P) :- explicit_default_policy(P).
active_default_policy(legacy) :- not configured_default_policy.

default_assumption_weight(W) :-
    active_default_policy(P),
    semiring_default_weight(P, W).

:- active_default_policy(P), not semiring_default_weight(P, _).


semiring_default_weight(legacy,#sup).
semiring_default_weight(aba,#sup).
semiring_default_weight(neutral,0).

%% =============================================
%% CLASSICAL ABA RECOVERY (No Discarding)
%% =============================================
%%
%% To recover plain unweighted ABA behavior with this semiring:
%%
%% UPPER BOUND REGIME (MAX, SUM, COUNT, LEX monoids):
%%   δ = #sup     (default weight for unweighted assumptions)
%%   β = 0        (budget value)
%%   Mechanism: constraint/ub.lp explicitly rejects discarding #sup-weighted attacks
%%
%% LOWER BOUND REGIME (MIN monoid):
%%   δ = #inf     (default weight for unweighted assumptions)
%%   β = 0        (budget value)
%%   Mechanism: MIN(#inf) = #inf < 0, rejected by constraint/lb.lp
%%   Alternative: δ = #sup with special constraint rejection
%%
%% CURRENT IMPLEMENTATION: δ = #sup (see line ~52 below)
%% This enables ABA recovery for UB monoids with β = 0.
%% For LB monoids, use δ = #inf by setting all assumption weights explicitly.

%% ========================================
%% DEFAULT WEIGHT PRINCIPLE: SUPREMUM
%% ========================================
%%
%% Unweighted atoms receive the SUPREMUM (maximum value in range):
%% - Matches standard ABA: assumptions accepted by default ("innocent until proven guilty")
%% - "Hardest to discard": attacks from unweighted atoms are maximally expensive
%% - Budget semantics: attacks with cost #sup (∞) CANNOT be discarded
%%
%% For Tropical:
%% - Supremum = #sup (∞, infinite cost)
%% - Meaning: Unweighted assumptions have infinite cost (unbounded)
%% - Discard cost with max monoid: max(#sup, ...) = #sup (impossible to discard!)
%% - Discard cost with min monoid: min(#sup, ...) = other values (doesn't contribute)
%% - Discard cost with sum monoid: sum + #sup = #sup (impossible to discard!)
%%
%% Note: This makes unweighted attacks IMPOSSIBLE to discard (not just expensive).
%% Only attacks with explicit finite costs can be discarded within budget constraints.
%%
%% Explicit weights REPLACE the supremum default (via mutually exclusive rules).
%% DEFAULT WEIGHTS for unweighted atoms are now defined in monoid/*.lp files,
%% since the monoid determines what "hard to discard" means.
%%

%% Assumptions with explicit weights
%% FLAT-WABA: assumption is not a rule head
%% NON-FLAT-WABA: if assumption is also a rule head, weight is computed below via rule derivation
supported_with_weight(X,W) :- assumption(X), in(X), weight(X,W), not head(_,X).

%% Assumptions without explicit weights: Use supremum (infinite cost)
%% For Tropical semiring, unweighted assumptions get #sup (infinite cost)
%% Rationale: Unweighted assumptions are "hardest to discard" (default acceptance)
%% - #sup = positive infinity (infinite cost)
%% - Matches standard ABA: assumptions accepted by default
%% - In conjunction (+): #sup + x = #sup (infinite cost propagates)
%% - In disjunction (min): min(#sup, x) = x (doesn't dominate)
%%
%% NOTE: Uses #sup (positive infinity) as supremum.
%% Constraints must handle #sup specially for budget checking.
%%
%% FLAT-WABA: assumption is not a rule head
%% NON-FLAT-WABA: if assumption is also a rule head, weight is computed below via rule derivation
supported_with_weight(X,W) :-
    assumption(X),
    in(X),
    not weight(X,_),
    not head(_,X),
    default_assumption_weight(W).

%% Step 1: Compute weight for each rule derivation using conjunction (addition)
%% For rule R deriving X: sum the weights of all body elements
%% IMPORTANT: Only compute weight for TRIGGERED rules (all body elements supported)
%%
%% Special handling for #sup: clingo's #sum aggregate ignores #sup values
%% If ANY body element has weight #sup, result is #sup (infinite cost propagates)

%% Helper: detect if any body element has #sup weight
body_has_sup_weight(R) :- body(R,B), supported_with_weight(B,#sup).

%% If any body has #sup, derivation weight is #sup (infinite cost)
rule_derivation_weight(R,X,#sup) :-
    head(R,X),
    supported(X),
    body(R,_),
    triggered_by_in(R),
    body_has_sup_weight(R).

%% Otherwise, sum finite weights (no #sup values present)
rule_derivation_weight(R,X,W) :-
    head(R,X),
    supported(X),
    body(R,_),
    triggered_by_in(R),
    not body_has_sup_weight(R),
    W = #sum{ V,B : body(R,B), supported_with_weight(B,V) }.

%% Handle rules with empty bodies (facts): Use 0 (multiplicative identity for +)
%% An empty body is an empty CONJUNCTION, so it must equal the multiplicative (⊗)
%% identity = 0. This keeps the empty body TRANSPARENT in + (0+x=x), so a fact used
%% inside a longer rule body contributes nothing to the accumulated cost.
%%
%% (Earlier this used #sup, the ADDITIVE identity. But #sup is the +-ANNIHILATOR
%% (x+#sup=#sup), so any conclusion derived through a fact collapsed to #sup,
%% poisoning every conjunctive chain through a fact. Classical ABA recovery is
%% preserved via constraint/no_discard.lp, which forbids discarding regardless of weight.)
rule_derivation_weight(R,X,0) :-
    head(R,X),
    supported(X),
    not body(R,_),
    not weight(X,_).  % weighted facts keep their explicit weight (override)

%% Step 2: Combine multiple derivations using disjunction (minimum)
%% IMPORTANT: Use DISJUNCTION OPERATOR (⊕) to combine weights from different paths:
%% - Multiple rule derivations are combined via ⊕
%% - Explicit weight is another "path" to support, combined via ⊕
%% - For Tropical semiring: ⊕ = min (choose best/cheapest path)
%%
%% SEMANTICS: Explicit weight + derived weight represent ALTERNATIVE support paths.
%% The actual weight is their DISJUNCTION, not conjunction or override.
%%
%% Example: If X has explicit weight 50 and is also derived with weight 30,
%%          then supported_with_weight(X, min(50, 30)) = supported_with_weight(X, 30)
%%          (the cheaper path is chosen)
supported_with_weight(X,W) :-
    supported(X),
    head(_,X),  % X is derived (not just an assumption)
    not assumption(X),  % X is not an assumption
    W = #min{ V,R : rule_derivation_weight(R,X,V) ;
              V : weight(X,V) }.  % DISJUNCTION (⊕ = min for Tropical)

%% NON-FLAT-WABA: Derived assumption with explicit weight
%% Combine rule-derived weight with explicit weight via DISJUNCTION (min)
supported_with_weight(X,W) :-
    assumption(X),
    supported(X),
    head(_,X),  % Assumption is also derived
    weight(X,_),  % Has explicit weight
    W = #min{ V,R : rule_derivation_weight(R,X,V) ;
              V : weight(X,V) }.  % DISJUNCTION (⊕ = min for Tropical)

%% NON-FLAT-WABA: Derived assumption WITHOUT explicit weight, but is IN
%% Combine rule-derived weight with default assumption weight (#sup) via DISJUNCTION (min)
supported_with_weight(X,W) :-
    assumption(X),
    in(X),  % Assumption is selected
    supported(X),
    head(_,X),  % Assumption is also derived
    not weight(X,_),  % No explicit weight
    default_assumption_weight(D),
    W = #min{ V,R : rule_derivation_weight(R,X,V) ;
              D : true }.  % Direct assumption path selected by the active default policy

%% ========================================================================
%% UNDEFEATED WEIGHT COMPUTATION (for Budget-Aware Admissibility Defense)
%% ========================================================================
%%
%% Mirrors supported_with_weight logic but for derived_from_undefeated elements.
%% Used to compute potential attack weights for defense checking.

%% Base case: Undefeated assumptions without explicit weights get #sup
undefeated_weight(X,W) :-
    assumption(X),
    not defeated(X),
    not weight(X,_),
    not head(_,X),
    default_assumption_weight(W).

%% FLAT-WABA: Undefeated assumptions with explicit weights (not rule heads)
undefeated_weight(X,W) :- assumption(X), not defeated(X), weight(X,W), not head(_,X).

%% Helper: detect if any body element has #sup weight in undefeated derivation
undefeated_body_has_sup(R) :- body(R,B), undefeated_weight(B,#sup).

%% Rule derivation weight for undefeated: sum body weights (with #sup propagation)
undefeated_rule_weight(R,X,#sup) :-
    head(R,X),
    derived_from_undefeated(X),
    body(R,_),
    triggered_by_undefeated(R),
    undefeated_body_has_sup(R).

undefeated_rule_weight(R,X,W) :-
    head(R,X),
    derived_from_undefeated(X),
    body(R,_),
    triggered_by_undefeated(R),
    not undefeated_body_has_sup(R),
    W = #sum{ V,B : body(R,B), undefeated_weight(B,V), V != #sup }.

%% Regular derived element: take minimum across all derivations (disjunction)
undefeated_weight(X,W) :-
    derived_from_undefeated(X),
    head(_,X),
    not assumption(X),
    W = #min{ V,R : undefeated_rule_weight(R,X,V) }.

%% NON-FLAT-WABA: Assumption that is also a rule head, WITH explicit weight
undefeated_weight(X,W) :-
    assumption(X),
    not defeated(X),
    derived_from_undefeated(X),
    head(_,X),
    weight(X,_),
    W = #min{ V,R : undefeated_rule_weight(R,X,V) ;
              V : weight(X,V) }.

%% NON-FLAT-WABA: Assumption that is also a rule head, WITHOUT explicit weight
undefeated_weight(X,W) :-
    assumption(X),
    not defeated(X),
    derived_from_undefeated(X),
    head(_,X),
    not weight(X,_),
    default_assumption_weight(D),
    W = #min{ V,R : undefeated_rule_weight(R,X,V) ;
              D : true }.

%% Polarity: Cost (lower is better)
%% Special case: beta=0 means classical ABA (all attacks unaffordable)
unaffordable_attack(W,B) :- undefeated_weight(_,W), budget(B), B = 0, W != #inf.
unaffordable_attack(W,B) :- undefeated_weight(_,W), budget(B), B != 0, W > B.
`,
        "tropical_high": `%% ALIAS — not a separate algebra.
%% \`tropical_high\` is the higher-is-better (reward) polarity dual of \`tropical\` (min,+).
%% That dual is exactly the (max, +) arctic algebra, so this file is a thin alias for
%% semiring/arctic.lp. Kept so that \`--semiring tropical_high\` and raw
%% \`clingo ... semiring/tropical_high.lp ...\` runs keep resolving.
%% Arctic (Max-Plus) Semiring for Weight Propagation
%% Semiring: (ℤ ∪ {±∞}, max, +, #inf, 0)
%% - Domain: ℤ ∪ {±∞} (integers plus positive/negative infinity)
%% - Disjunction/⊕ (OR): max (strongest alternative)
%% - Conjunction/⊗ (AND): + (accumulate rewards)
%% - Additive identity: #inf (identity for max operation)
%% - Multiplicative identity: 0 (identity for + operation)
%% - Interpretation: weights are rewards/benefits, higher is better
%%
%% SEMANTICS: Reward Accumulation / Longest Path
%% ==============================================
%% The Arctic semiring is the DUAL of the Tropical semiring:
%% - Tropical: (+, min) for cost minimization / shortest path
%% - Arctic: (+, max) for reward maximization / longest path
%%
%% Key applications:
%% - Scoring arguments by accumulated support/evidence
%% - Finding strongest evidence chains (sum of supporting weights)
%% - Benefit/reward optimization (opposite of cost minimization)
%% - Longest path problems in graphs
%%
%% Comparison to Tropical:
%% - Tropical: weights are costs (lower is better), minimize sum
%% - Arctic: weights are rewards (higher is better), maximize sum
%%
%% Note: "Arctic" comes from tropical algebra (hot=min, cold=max)

active_semiring(arctic).
%% Default weight policy selection for unweighted assumptions.
%%
%% Semiring modules provide semiring_default_weight(policy, value).
%% Callers may optionally load one explicit policy module from defaults/.
%% If none is loaded, legacy behavior is preserved.

configured_default_policy :- explicit_default_policy(_).

:- explicit_default_policy(P1), explicit_default_policy(P2), P1 != P2.

active_default_policy(P) :- explicit_default_policy(P).
active_default_policy(legacy) :- not configured_default_policy.

default_assumption_weight(W) :-
    active_default_policy(P),
    semiring_default_weight(P, W).

:- active_default_policy(P), not semiring_default_weight(P, _).


semiring_default_weight(legacy,0).
semiring_default_weight(aba,#sup).
semiring_default_weight(neutral,0).

%% ========================================
%% DEFAULT WEIGHT PRINCIPLE: NEUTRALITY
%% ========================================
%%
%% Unweighted atoms receive the MULTIPLICATIVE IDENTITY (0):
%% - For addition: 0 + x = x (neutral, doesn't affect accumulation)
%% - Default weight of 0 means "no reward contributed"
%%
%% IMPORTANT: This differs from Tropical semiring!
%% - Tropical uses #sup as default (infinitely expensive to discard)
%% - Arctic uses 0 as default (neutral contribution, easily discarded)
%%
%% For Arctic semiring:
%% - Multiplicative identity = 0 (neutral for addition)
%% - Meaning: Unweighted assumptions contribute zero reward
%% - Discard cost with max monoid: max(0, ...) = other weights (not dominating)
%% - Discard cost with sum monoid: sum + 0 = sum (neutral)
%%
%% This creates different semantics than Tropical:
%% - Tropical: Unweighted assumptions are "hard to discard" (#sup)
%% - Arctic: Unweighted assumptions are "neutral" (0 reward)
%%
%% If you want unweighted assumptions to be "hard to discard" in Arctic,
%% the monoid should assign #sup as default (monoid/*.lp files handle this).

%% Assumptions with explicit weights
supported_with_weight(X,W) :- assumption(X), in(X), weight(X,W), not head(_,X).

%% Assumptions without explicit weights: Use multiplicative identity (0)
%% For Arctic semiring, unweighted assumptions get 0 (neutral reward)
%% Rationale: Neutral contribution to reward accumulation
%% - In conjunction (+): 0 + x = x (doesn't affect sum)
%% - In disjunction (max): max(0, x) = x for x > 0 (neutral for positive rewards)
%%
%% NOTE: This is the MULTIPLICATIVE identity (neutral for conjunction).
%% For "hard to discard" semantics, monoids assign #sup as default weight.
supported_with_weight(X,W) :- assumption(X), in(X), not weight(X,_), not head(_,X), default_assumption_weight(W).

%% Step 1: Compute weight for each rule derivation using conjunction (addition)
%% For rule R deriving X: sum weights of all body elements (accumulate rewards)
%% IMPORTANT: Only compute weight for TRIGGERED rules (all body elements supported)

%% Special handling for #sup and #inf: clingo's #sum aggregate has limitations
%% - #sum ignores #sup values (with warning)
%% - #inf is handled correctly
%% We detect infinite values before aggregation to preserve them

%% Helper: detect if any body element has #sup weight (infinite reward)
body_has_sup_weight(R) :- body(R,B), supported_with_weight(B,#sup).

%% Helper: detect if any body element has #inf weight (infinitely negative)
body_has_inf_weight(R) :- body(R,B), supported_with_weight(B,#inf).

%% If any body has #sup, derivation weight is #sup (infinite reward propagates)
rule_derivation_weight(R,X,#sup) :-
    head(R,X),
    supported(X),
    body(R,_),
    triggered_by_in(R),
    body_has_sup_weight(R).

%% If any body has #inf (and no #sup), derivation weight is #inf
rule_derivation_weight(R,X,#inf) :-
    head(R,X),
    supported(X),
    body(R,_),
    triggered_by_in(R),
    not body_has_sup_weight(R),
    body_has_inf_weight(R).

%% Otherwise, sum finite weights (standard case)
rule_derivation_weight(R,X,W) :-
    head(R,X),
    supported(X),
    body(R,_),
    triggered_by_in(R),
    not body_has_sup_weight(R),
    not body_has_inf_weight(R),
    W = #sum{ V,B : body(R,B), supported_with_weight(B,V) }.

%% Handle rules with empty bodies (facts): Use 0 (multiplicative identity for +)
%% An empty body is an empty CONJUNCTION, so it must equal the multiplicative (⊗)
%% identity = 0. This keeps the empty body TRANSPARENT in + (0+x=x); over the
%% supported (nonnegative) weight surface a standalone fact then carries 0 reward.
%%
%% (Earlier this used #inf, the ADDITIVE identity. #inf is dropped/absorbed by the
%% reward-accumulating +, so conclusions derived through a fact were corrupted.
%% Classical ABA recovery is preserved via constraint/no_discard.lp.)
rule_derivation_weight(R,X,0) :-
    head(R,X),
    supported(X),
    not body(R,_),
    not weight(X,_).  % weighted facts keep their explicit weight (override)

%% Step 2: Combine multiple derivations using disjunction (maximum)
%% The weight of X is the maximum across all its rule derivations
%% AND any explicit weight (OR semantics: explicit weight is another "derivation")
%% Interpretation: Multiple derivation paths → take strongest/highest reward path
supported_with_weight(X,W) :-
    supported(X),
    head(_,X),  % X is derived (not just an assumption)
    W = #max{ V : rule_derivation_weight(_,X,V) ;
              V : weight(X,V) }.

%% ========================================================================
%% UNDEFEATED WEIGHT COMPUTATION (for Budget-Aware Admissibility Defense)
%% ========================================================================

%% Base cases
undefeated_weight(X,W) :-
    assumption(X),
    not defeated(X),
    not weight(X,_),
    not head(_,X),
    default_assumption_weight(W).
undefeated_weight(X,W) :- assumption(X), not defeated(X), weight(X,W), not head(_,X).

%% Rule derivation with Arctic conjunction (addition)
undefeated_rule_weight(R,X,W) :-
    head(R,X),
    derived_from_undefeated(X),
    body(R,_),
    triggered_by_undefeated(R),
    W = #sum{ V,B : body(R,B), undefeated_weight(B,V) }.

%% Disjunction (max)
undefeated_weight(X,W) :-
    derived_from_undefeated(X),
    head(_,X),
    not assumption(X),
    W = #max{ V,R : undefeated_rule_weight(R,X,V) }.

%% NON-FLAT: Assumptions that are also rule heads
undefeated_weight(X,W) :-
    assumption(X),
    not defeated(X),
    derived_from_undefeated(X),
    head(_,X),
    weight(X,_),
    W = #max{ V,R : undefeated_rule_weight(R,X,V) ;
              V : weight(X,V) }.

undefeated_weight(X,W) :-
    assumption(X),
    not defeated(X),
    derived_from_undefeated(X),
    head(_,X),
    not weight(X,_),
    default_assumption_weight(D),
    W = #max{ V,R : undefeated_rule_weight(R,X,V) ;
              D : true }.

%% Polarity: Strength (higher is better)
%% Classical ABA: beta=#sup (can't meet threshold) or beta=0 (backward compatibility)
unaffordable_attack(W,B) :- undefeated_weight(_,W), budget(B), B = #sup, W != #sup.
unaffordable_attack(W,B) :- undefeated_weight(_,W), budget(B), B = 0, W != #inf.
unaffordable_attack(W,B) :- undefeated_weight(_,W), budget(B), B != #sup, B != 0, W < B.

`
    },
    defaults: {
        "aba": `%% Use ABA-recovery defaults for unweighted assumptions.
%% This chooses the semiring-specific "hard to discard" value.
explicit_default_policy(aba).
`,
        "base": `%% Default weight policy selection for unweighted assumptions.
%%
%% Semiring modules provide semiring_default_weight(policy, value).
%% Callers may optionally load one explicit policy module from defaults/.
%% If none is loaded, legacy behavior is preserved.

configured_default_policy :- explicit_default_policy(_).

:- explicit_default_policy(P1), explicit_default_policy(P2), P1 != P2.

active_default_policy(P) :- explicit_default_policy(P).
active_default_policy(legacy) :- not configured_default_policy.

default_assumption_weight(W) :-
    active_default_policy(P),
    semiring_default_weight(P, W).

:- active_default_policy(P), not semiring_default_weight(P, _).
`,
        "legacy": `%% Preserve the pre-refactor default behavior for unweighted assumptions.
explicit_default_policy(legacy).
`,
        "neutral": `%% Use the semiring-specific conjunction-neutral default for unweighted assumptions.
explicit_default_policy(neutral).
`
    },
    monoid: {
        "max": `%% Max monoid family.
%% Aggregate: maximum discarded attack weight.
%% Identity on the empty set: #inf.

active_monoid(max).
`,
        "min": `%% Min monoid family.
%% Aggregate: minimum discarded attack weight.
%% Identity on the empty set: #sup.

active_monoid(min).
`,
        "sum": `%% Sum monoid family.
%% Aggregate: sum of discarded attack weights.
%% Identity on the empty set: 0.

active_monoid(sum).
`
    },
    optimize: {
        "maximize": `%% Generic maximization objective over the active monoid family.

active_optimization(maximize).

:- active_optimization(minimize).
:- not active_monoid(sum), not active_monoid(max), not active_monoid(min).
:- 2 { active_monoid(sum); active_monoid(max); active_monoid(min) }.

#maximize { W,X,Y : active_monoid(sum), discarded_attack(X,Y,W) }.

:~ active_monoid(max), M = #max { W : discarded_attack(_,_,W) }, M = #inf. [1@2]
:~ active_monoid(max), M = #max { W : discarded_attack(_,_,W) }, M != #sup. [-1@1]
:~ active_monoid(max), M = #max { W : discarded_attack(_,_,W) }, M != #sup, M != #inf. [-M@0]

:~ active_monoid(min), M = #min { W : discarded_attack(_,_,W) }, M = #inf. [1@2]
:~ active_monoid(min), M = #min { W : discarded_attack(_,_,W) }, M != #inf. [-1@1]
:~ active_monoid(min), M = #min { W : discarded_attack(_,_,W) }, M != #sup, M != #inf. [-M@0]
`,
        "minimize": `%% Generic minimization objective over the active monoid family.

active_optimization(minimize).

:- active_optimization(maximize).
:- not active_monoid(sum), not active_monoid(max), not active_monoid(min).
:- 2 { active_monoid(sum); active_monoid(max); active_monoid(min) }.

#minimize { W,X,Y : active_monoid(sum), discarded_attack(X,Y,W) }.

:~ active_monoid(max), M = #max { W : discarded_attack(_,_,W) }, M = #sup. [1@2]
:~ active_monoid(max), M = #max { W : discarded_attack(_,_,W) }, M = #inf. [0@1]
:~ active_monoid(max), M = #max { W : discarded_attack(_,_,W) }, M != #sup, M != #inf. [M@0]

:~ active_monoid(min), M = #min { W : discarded_attack(_,_,W) }, M = #inf. [1@2]
:~ active_monoid(min), M = #min { W : discarded_attack(_,_,W) }, M = #sup. [0@1]
:~ active_monoid(min), M = #min { W : discarded_attack(_,_,W) }, M != #sup, M != #inf. [M@0]
`
    },
    constraint: {
        "lb": `%% Generic lower-bound budget constraint.

active_budget_mode(lb).
active_constraint(lb).

:- not active_monoid(sum), not active_monoid(max), not active_monoid(min).
:- 2 { active_monoid(sum); active_monoid(max); active_monoid(min) }.

budget_value(C) :- active_monoid(sum), C = #sum{ W,X,Y : discarded_attack(X,Y,W) }.
budget_value(C) :- active_monoid(max), C = #max{ W : discarded_attack(_,_,W) }.
budget_value(C) :- active_monoid(min), C = #min{ W : discarded_attack(_,_,W) }.

%% An empty discard set spends nothing; it does not "meet" a positive lower bound,
%% but it must remain FEASIBLE (the no-discard extension always exists). Without this
%% guard the max monoid breaks: #max{} over no discards = #inf < beta, which would
%% reject the no-discard extension outright. The min empty aggregate (#sup) already
%% passes a lower bound, so guarding only changes the otherwise-broken max+lb case.
some_discard :- discarded_attack(_,_,_).
:- budget_value(C), C < B, budget(B), some_discard.
:- discarded_attack(_,_,#sup).
`,
        "no_discard": `%% No Discarding Constraint
%% =========================
%%
%% Enforces classical ABA by forcing the discard set to be empty
%%
%% Use with: Any semantic file for pure ABA/ASPforABA compatibility
%%
%% Semantics: direct no-discard profile, independent of monoid loading
%%
%% Usage:
%%   clingo -n 0 WABA/core/base.lp WABA/semiring/godel.lp \\
%%          WABA/constraint/no_discard.lp WABA/filter/standard.lp \\
%%          WABA/semantics/<semantic>.lp framework.lp

%% Reject any extension that discards any attack
active_budget_mode(no_discard).
active_constraint(no_discard).
:- discarded_attack(_,_,_).
`,
        "ub": `%% Generic upper-bound budget constraint.

active_budget_mode(ub).
active_constraint(ub).

:- not active_monoid(sum), not active_monoid(max), not active_monoid(min).
:- 2 { active_monoid(sum); active_monoid(max); active_monoid(min) }.

budget_value(C) :- active_monoid(sum), C = #sum{ W,X,Y : discarded_attack(X,Y,W) }.
budget_value(C) :- active_monoid(max), C = #max{ W : discarded_attack(_,_,W) }.
budget_value(C) :- active_monoid(min), C = #min{ W : discarded_attack(_,_,W) }.

%% An empty discard set spends nothing, so it trivially respects any upper bound.
%% Without this guard the min monoid breaks: #min{} over no discards = #sup, which
%% would spuriously exceed every finite beta and reject the (cost-free) no-discard
%% extension. The max/sum empty aggregates (#inf/0) already pass an upper
%% bound, so guarding only changes the otherwise-broken min+ub case.
some_discard :- discarded_attack(_,_,_).
:- budget_value(C), C > B, budget(B), some_discard.
:- discarded_attack(_,_,#sup).
`
    },
    filter: {
        "projection": `%% Output filtering for projection mode: show in/out and discarded attacks
#show in/1.
#show out/1.
#show discarded_attack/3.
`,
        "standard": `#show in/1.
#show out/1.
#show undec/1.
#show supported_with_weight/2.
#show attacks_successfully_with_weight/3.
#show discarded_attack/3.

% Framework structure (needed for attack derivation tracing)
#show assumption/1.
#show contrary/2.
#show head/2.
#show body/2.
`
    },
    semantics: {
        "admissible": `defeated(X) :- attacks_successfully_with_weight(_,X,_).
1{ in(X); out(X) }1 :- assumption(X).
:- in(X), defeated(X).

%% Admissibility

derived_from_undefeated(X) :- assumption(X), not defeated(X).
derived_from_undefeated(X) :- head(R,X), triggered_by_undefeated(R).
triggered_by_undefeated(R) :- rule(R), derived_from_undefeated(X) : body(R,X).
attacked_by_undefeated(X) :- contrary(X,Y), undefeated_weight(Y,W), budget(B), unaffordable_attack(W,B).
:- in(X), attacked_by_undefeated(X).
`,
        "cf": `defeated(X) :- attacks_successfully_with_weight(_,X,_).
1{ in(X); out(X) }1 :- assumption(X).
:- in(X), defeated(X).`,
        "complete": `%% Complete Semantics
%% Builds upon: Admissible

defeated(X) :- attacks_successfully_with_weight(_,X,_).
1{ in(X); out(X) }1 :- assumption(X).
:- in(X), defeated(X).

%% Admissibility

derived_from_undefeated(X) :- assumption(X), not defeated(X).
derived_from_undefeated(X) :- head(R,X), triggered_by_undefeated(R).
triggered_by_undefeated(R) :- rule(R), derived_from_undefeated(X) : body(R,X).
attacked_by_undefeated(X) :- contrary(X,Y), undefeated_weight(Y,W), budget(B), unaffordable_attack(W,B).
:- in(X), attacked_by_undefeated(X).


%% Completeness: All unattacked assumptions must be IN
%% If an assumption is not attacked by any undefeated element, it must be in the extension
:- out(X), assumption(X), not attacked_by_undefeated(X).

`,
        "grounded": `%% Grounded Semantics
%% Minimal complete extension
%%
%% Implementation: Minimize |in| subject to completeness
%% Priority @5 ensures semantic selection precedes cost optimization

%% Complete Semantics
%% Builds upon: Admissible

defeated(X) :- attacks_successfully_with_weight(_,X,_).
1{ in(X); out(X) }1 :- assumption(X).
:- in(X), defeated(X).

%% Admissibility

derived_from_undefeated(X) :- assumption(X), not defeated(X).
derived_from_undefeated(X) :- head(R,X), triggered_by_undefeated(R).
triggered_by_undefeated(R) :- rule(R), derived_from_undefeated(X) : body(R,X).
attacked_by_undefeated(X) :- contrary(X,Y), undefeated_weight(Y,W), budget(B), unaffordable_attack(W,B).
:- in(X), attacked_by_undefeated(X).


%% Completeness: All unattacked assumptions must be IN
%% If an assumption is not attacked by any undefeated element, it must be in the extension
:- out(X), assumption(X), not attacked_by_undefeated(X).



%% MAIN (@5): Minimize cardinality of extension to find grounded (minimal complete)
%% Priority @5 ensures separation from cost optimization (@1-@3)
#minimize { 1@5, X : in(X) }.

`,
        "stable": `%% Guess an extension
1{ in(X); out(X) }1 :- assumption(X).

%% Conflict-free on successful attacks
:- supported(X), in(Y), attacks_successfully_with_weight(X,Y,_).

%% Defeated-by-S (counterattacked)
defeated(Y) :- supported(Z), assumption(Y), attacks_successfully_with_weight(Z,Y,_).

%% stable
:- not defeated(X), out(X).
`,
        "subset_maximal_filter": `%% Exact subset-maximal filtering over precomputed candidate extensions.
%%
%% Expected facts:
%%   candidate(M).
%%   member(M,A).
%%
%% Output:
%%   keep(M).
%%
%% Rationale:
%%   exact subset-maximality is a set-inclusion property; it is kept separate
%%   from WABA's numeric weight optimization layer instead of being encoded with
%%   plain #maximize priority levels.

model_pair(I,J) :- candidate(I), candidate(J), I != J.

not_subset(I,J) :- model_pair(I,J), member(I,A), not member(J,A).
has_extra(J,I) :- model_pair(I,J), member(J,A), not member(I,A).

strict_subset(I,J) :-
    model_pair(I,J),
    not not_subset(I,J),
    has_extra(J,I).

dominated(I) :- strict_subset(I,J).
keep(I) :- candidate(I), not dominated(I).

#show keep/1.
`
    },
    examples: {
        "simple_attack": `%% Simple test framework for comparing WABA semantics with ASPARTIX
%%
%% Structure: a attacks b, c is independent
%%
%% Expected (classical ABA / AAF):
%%   Stable: {a,c}
%%   Admissible: {}, {a}, {c}, {a,c}
%%   Complete: {a,c}
%%   Grounded: {a,c}
%%   Preferred: {a,c}

assumption(a).
assumption(b).
assumption(c).

% a attacks b
contrary(b, a).

% Weights (all equal for plain ABA behavior)
weight(a, 1).
weight(b, 1).
weight(c, 1).

% Budget definition for constraint files
% Use beta=0 for plain ABA (no attack discarding)
#const beta = 0.
budget(beta).
`,
        "practical_deliberation": `%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% PRACTICAL DELIBERATION - Commonsense Default Reasoning for Daily Planning
%%
%% STORY:
%% An agent planning a Sunday routine relies on four defeasible default beliefs:
%% traffic is light on Sundays, gym opens at 7am, no rain expected, no meetings.
%% These defaults generate action plans. Unexpected events (gym_closed,
%% traffic_heavy, rain_detected, meeting_scheduled) defeat defaults, forcing
%% belief revision. We minimize total revision cost (cognitive parsimony).
%%
%% WEIGHT INTERPRETATION:
%% Weights represent cognitive revision cost (1-10, belief entrenchment).
%% Higher weights = more entrenched belief (harder to revise).
%%
%% SEMIRING: Arctic (sum/max, dual of Tropical)
%% JUSTIFICATION: Belief strength accumulates (reward-based). Stronger defaults
%% = higher cumulative value. Arctic is dual of Tropical (identity 0, not #sup).
%%
%% MONOID: Sum
%% JUSTIFICATION: Extension cost = total revision cost (sum of the disruption
%% weights of the overridden defaults). Heavier defaults cost more to revise.
%%
%% OPTIMIZATION: Minimize
%% JUSTIFICATION: Minimize total revision cost (cognitive conservatism).
%%
%% BUDGET β: Upper bound on total revision cost.
%% β = 20 means "spend at most 20 total on revisions"
%%
%% DISCARDED ATTACK INTERPRETATION:
%% Overriding a disruption = maintaining the default despite contrary evidence
%% (cost = that disruption's weight). We sum the cost of the defaults we abandon.
%%
%% USAGE:
%% clingo -n 0 --opt-mode=optN -c beta=20 \\
%%   WABA/core/base.lp \\
%%   WABA/semiring/arctic.lp \\
%%   WABA/monoid/sum.lp \\
%%   WABA/optimize/minimize.lp \\
%%   WABA/constraint/ub.lp \\
%%   WABA/filter/standard.lp \\
%%   WABA/semantics/stable.lp \\
%%   WABA/examples/practical_deliberation/practical_deliberation.lp
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Budget parameter (override via -c beta=N)
#const beta = 20.

%% ============================================================================
%% ASSUMPTIONS (Commonsense Defaults)
%% ============================================================================

assumption(assume_traffic_light).  % Default: Sunday traffic is light
assumption(assume_gym_open).       % Default: Gym open at 7am
assumption(assume_weather_good).   % Default: No rain expected
assumption(assume_no_meeting).     % Default: No Sunday meetings

%% ============================================================================
%% WEIGHTS (Belief Entrenchment - for Arctic semiring)
%% ============================================================================

%% Default belief weights (entrenchment 1-10)
weight(assume_traffic_light, 8).   % Highly entrenched: Sundays are usually quiet
weight(assume_gym_open, 7).         % Moderately entrenched: Usually open
weight(assume_weather_good, 6).     % Less entrenched: Weather variable
weight(assume_no_meeting, 9).       % Very entrenched: Rarely meet Sundays

%% Disruption weights (summed by the Sum monoid as total revision cost)
weight(gym_closed, 7).
weight(traffic_heavy, 8).
weight(rain_detected, 6).
weight(meeting_scheduled, 9).

%% Plan weights
weight(plan_early_workout, 5).
weight(plan_drive_downtown, 6).
weight(plan_outdoor_run, 5).

%% ============================================================================
%% RULES (Defaults → Plans, Disruptions Defeat Defaults)
%% ============================================================================

%% r1: Gym open default → plan early workout
head(r1, plan_early_workout).
body(r1, assume_gym_open).

%% r2: Light traffic default → plan to drive
head(r2, plan_drive_downtown).
body(r2, assume_traffic_light).

%% r3: Good weather default → plan outdoor run
head(r3, plan_outdoor_run).
body(r3, assume_weather_good).

%% r4: Gym closed observed → disruption
head(r4, gym_closed).
% No body - this is an observed fact (gym unexpectedly closed on Sundays)

%% r5: Traffic report shows heavy traffic → disruption
head(r5, traffic_heavy).
% No body - unexpected traffic due to event

%% r6: Weather update shows rain → disruption
head(r6, rain_detected).
% No body - forecast updated

%% r7: Meeting invitation received → disruption
head(r7, meeting_scheduled).
% No body - unexpected Sunday meeting

%% ============================================================================
%% CONTRARIES (Disruptions Defeat Defaults)
%% ============================================================================

contrary(assume_gym_open, gym_closed).
contrary(assume_traffic_light, traffic_heavy).
contrary(assume_weather_good, rain_detected).
contrary(assume_no_meeting, meeting_scheduled).

%% ============================================================================
%% BUDGET CONSTRAINT
%% ============================================================================

%% Budget constraint enforced by loading constraint/ub.lp
%% (total revision cost ≤ β)
`,
        "probabilistic": `%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% WEIGHTS AS PROBABILITIES — most-probable-proof (Viterbi) WABA
%%
%% Probabilities MULTIPLY along a derivation; -ln turns product into sum, so the
%% TROPICAL semiring (min,+) computes the most-probable proof (Viterbi):
%%
%%   encode:  w = round(-1000 * ln p)     (p in (0,1] -> integer w >= 0; p=1 -> 0)
%%   decode:  p = exp(-w / 1000)
%%
%%   conjunction (rule body)   : +   over body  = surprisal of the product of premises
%%   disjunction (derivations) : min            = the most probable proof
%%
%% This is the Viterbi semiring ([0,1], max, x) carried onto tropical (min,+) by the
%% order-isomorphism p |-> -ln p. (Full MARGINAL probabilities -- a sum over ALL
%% proofs -- would instead need the sum-product semiring, i.e. the ProbLog setting.)
%%
%% Probability table used below (p -> encoded weight):
%%   rain        p = 0.90  ->  105
%%   sprinkler   p = 0.70  ->  357
%%   cold_night  p = 0.50  ->  693
%%
%% SEMIRING : tropical (min,+), lower-is-better (smaller surprisal = more probable)
%% MONOID   : sum  (the dismissed attacks' surprisals add; ub budget beta bounds the
%%            JOINT probability of what you dismiss: sum <= beta  <=>  prod p >= e^-beta/1000)
%%
%% RUN (pure propagation; read supported_with_weight(X,w) and decode p = exp(-w/1000)):
%%   ./bin/waba run --framework examples/probabilistic/probabilistic.lp \\
%%        --semiring tropical --semantics stable --show standard
%%
%% RUN (budgeted: is the dry_path defence affordable? enumerate within beta):
%%   clingo -n 0 -c beta=800 core/base.lp semiring/tropical.lp monoid/sum.lp \\
%%        constraint/ub.lp filter/projection.lp semantics/stable.lp \\
%%        examples/probabilistic/probabilistic.lp
%%   The {rain,sprinkler,cold_night,dry_path} extension discards \`slippery\` at
%%   surprisal 798 (probability 0.45) and is feasible iff beta >= 798; it vanishes
%%   at beta < 798. (sum+ub bounds the JOINT probability of the dismissed attacks
%%   at >= exp(-beta/1000); under sum-min the optimiser instead prefers discarding
%%   nothing, i.e. dry_path out at cost 0.)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Probabilistic leaves (assumptions), weights = surprisals
assumption(rain).        weight(rain, 105).        % p = 0.90
assumption(sprinkler).   weight(sprinkler, 357).   % p = 0.70
assumption(cold_night).  weight(cold_night, 693).  % p = 0.50

%% grass_wet holds if it rained OR the sprinkler ran (two independent proofs)
head(r1, grass_wet).  body(r1, rain).        % grass_wet <- rain
head(r2, grass_wet).  body(r2, sprinkler).   % grass_wet <- sprinkler
%% => supported_with_weight(grass_wet, min(105,357)=105) -> p = e^-0.105 = 0.90
%%    (the most probable proof: it rained)

%% the path is slippery if the grass is wet AND the night is cold (frost)
head(r3, slippery).   body(r3, grass_wet).  body(r3, cold_night).   % slippery <- grass_wet, cold_night
%% => supported_with_weight(slippery, 105+693=798) -> p = e^-0.798 = 0.45 = 0.90 * 0.50

%% Default belief: the path is safe to walk. The (probabilistic) conclusion
%% \`slippery\` is its contrary, i.e. slippery attacks dry_path with weight 798.
assumption(dry_path).
contrary(dry_path, slippery).
%% Under sum+ub, dry_path can be accepted only by discarding the slippery attack,
%% at surprisal cost 798 (probability 0.45); beta caps that cost.
`,
        "aspforaba_journal_example": `%% Journal paper reference case from ASPforABA comparison work.
%% Expected classical results with no attack discarding:
%% - admissible: 7
%% - complete: 3
%% - stable: 2
%% - preferred: 2
%% - grounded: 1

assumption(a).
assumption(b).
assumption(c).
assumption(d).

contrary(b, x).
contrary(c, y).
contrary(d, z).

head(r1, w). body(r1, a).
head(r2, y). body(r2, b). body(r2, w).
head(r3, x). body(r3, c).
head(r4, z). body(r4, a). body(r4, b).

weight(a, 100).
weight(b, 100).
weight(c, 100).
weight(d, 100).
weight(w, 100).
weight(x, 100).
weight(y, 100).
weight(z, 100).

#const beta = 0.
budget(beta).
`,
        "scientific_theory": `%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% SCIENTIFIC THEORY CHOICE - Explanatory Power vs. Theoretical Complexity
%%
%% STORY:
%% A scientist must choose between competing theoretical hypotheses (Newtonian,
%% relativistic, quantum, auxiliary) to explain experimental data. Each theory,
%% combined with observational data, generates predictions. Theories conflict
%% when they make incompatible predictions (theoretical inconsistency). We
%% maximize explanatory power while bounding total theoretical complexity.
%%
%% WEIGHT INTERPRETATION:
%% Weights represent theoretical complexity cost (0-100). Higher weights =
%% more complex theory (harder to justify, higher cognitive burden).
%%
%% SEMIRING: Tropical (sum/min)
%% JUSTIFICATION: Explanatory power accumulates across phenomena. When a
%% theory explains multiple phenomena, the evidential support combines
%% additively (cumulative explanatory strength).
%%
%% MONOID: Sum
%% JUSTIFICATION: Extension cost = total theoretical complexity of discarded
%% inconsistencies. Each time we accept a theoretical conflict, we incur
%% complexity cost. Sum represents total complexity burden.
%%
%% OPTIMIZATION: Maximize explanatory adequacy via minimizing complexity cost
%% JUSTIFICATION: We want to maximize explanatory power. Using sum + minimize,
%% we minimize complexity cost, which is equivalent to maximizing explanatory
%% strength (simpler theories preferred, Ockham's razor).
%%
%% BUDGET β: Upper bound on total theoretical complexity.
%% β = 275 means "total complexity ≤ 275"
%%
%% DISCARDED ATTACK INTERPRETATION:
%% Overriding an inconsistency = accepting theoretical complexity (cost =
%% complexity penalty). We maintain incompatible theories by accepting the
%% complexity burden.
%%
%% USAGE:
%% clingo -n 0 --opt-mode=optN -c beta=275 \\
%%   WABA/core/base.lp \\
%%   WABA/semiring/tropical.lp \\
%%   WABA/monoid/sum.lp \\
%%   WABA/optimize/minimize.lp \\
%%   WABA/constraint/ub.lp \\
%%   WABA/filter/standard.lp \\
%%   WABA/semantics/stable.lp \\
%%   WABA/examples/scientific_theory/scientific_theory.lp
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Budget parameter (override via -c beta=N)
#const beta = 275.

%% ============================================================================
%% ASSUMPTIONS (Theoretical Hypotheses)
%% ============================================================================

assumption(assume_newtonian).         % Newtonian mechanics applies
assumption(assume_relativistic).      % Relativistic corrections needed
assumption(assume_quantum).           % Quantum effects relevant
assumption(assume_auxiliary_h1).      % Auxiliary hypothesis 1

%% ============================================================================
%% WEIGHTS (Theoretical Complexity)
%% ============================================================================

%% Theory complexity weights (0-100, higher = more complex)
weight(assume_newtonian, 30).         % Simplest theory
weight(assume_relativistic, 60).      % More complex
weight(assume_quantum, 70).           % Most complex fundamental theory
weight(assume_auxiliary_h1, 40).      % Auxiliary adds complexity

%% Inconsistency complexity weights (cost of accepting conflicts)
weight(incompatible_newtonian_quantum, 80).   % High complexity to maintain both
weight(incompatible_classical_relativistic, 65). % Moderate complexity
weight(excessive_complexity, 50).      % Too many auxiliary hypotheses

%% Prediction weights (explanatory contribution)
weight(predict_orbit_precession, 45).
weight(predict_time_dilation, 50).
weight(explain_photoelectric, 55).

%% Observational data weights
weight(observation_mercury_precession, 20).
weight(observation_gps_time_dilation, 25).
weight(observation_photoelectric_effect, 30).

%% ============================================================================
%% RULES (Theories + Observations → Predictions → Inconsistencies)
%% ============================================================================

%% r1-r3: Observational data (always holds)
head(r1, observation_mercury_precession).
head(r2, observation_gps_time_dilation).
head(r3, observation_photoelectric_effect).

%% r4: Relativistic theory + Mercury observation → predicts precession
head(r4, predict_orbit_precession).
body(r4, assume_relativistic).
body(r4, observation_mercury_precession).

%% r5: Relativistic theory + GPS observation → predicts time dilation
head(r5, predict_time_dilation).
body(r5, assume_relativistic).
body(r5, observation_gps_time_dilation).

%% r6: Quantum theory + photoelectric observation → explains effect
head(r6, explain_photoelectric).
body(r6, assume_quantum).
body(r6, observation_photoelectric_effect).

%% r7: Newtonian + Quantum theories together → incompatible (domain conflicts)
head(r7, incompatible_newtonian_quantum).
body(r7, assume_newtonian).
body(r7, assume_quantum).

%% r8: Classical (Newtonian) + Relativistic → incompatible for high velocities
head(r8, incompatible_classical_relativistic).
body(r8, assume_newtonian).
body(r8, assume_relativistic).

%% r9: Too many auxiliary hypotheses → excessive complexity
head(r9, excessive_complexity).
body(r9, assume_auxiliary_h1).
body(r9, assume_relativistic).
body(r9, assume_quantum).

%% ============================================================================
%% CONTRARIES (Theoretical Inconsistencies Defeat Hypotheses)
%% ============================================================================

contrary(assume_newtonian, incompatible_newtonian_quantum).
contrary(assume_quantum, incompatible_newtonian_quantum).
contrary(assume_newtonian, incompatible_classical_relativistic).
contrary(assume_auxiliary_h1, excessive_complexity).

%% ============================================================================
%% BUDGET CONSTRAINT
%% ============================================================================

%% Budget constraint enforced by loading constraint/ub.lp
%% (total complexity ≤ β)
`
    },
    metadata: {
        "generatedFrom": "ABA-variants/WABA",
        "semiringFamilies": [
            "godel",
            "tropical"
        ],
        "polarities": [
            "higher",
            "lower"
        ],
        "supportedSemiringKeys": [
            "arctic",
            "bottleneck_cost",
            "godel",
            "godel_low",
            "tropical",
            "tropical_high"
        ],
        "defaults": [
            "aba",
            "base",
            "legacy",
            "neutral"
        ],
        "monoids": [
            "max",
            "min",
            "sum"
        ],
        "optimizations": [
            "maximize",
            "minimize"
        ],
        "objectives": [
            "max-min",
            "max-max",
            "min-min",
            "min-max",
            "sum-min",
            "sum-max"
        ],
        "budgetModes": [
            "none",
            "ub",
            "lb"
        ],
        "supportedSemantics": [
            "cf",
            "stable",
            "admissible",
            "complete",
            "grounded",
            "preferred"
        ],
        "postFilteredSemantics": [
            "grounded",
            "preferred"
        ],
        "canonicalSemiring": {
            "godel": {
                "higher": "godel",
                "lower": "bottleneck_cost"
            },
            "tropical": {
                "higher": "arctic",
                "lower": "tropical"
            }
        },
        "aliases": {
            "godel_low": {
                "family": "godel",
                "polarity": "lower"
            },
            "tropical_high": {
                "family": "tropical",
                "polarity": "higher"
            }
        },
        "supportedBudgetPairs": [
            {
                "monoid": "max",
                "budgetMode": "ub"
            },
            {
                "monoid": "min",
                "budgetMode": "lb"
            },
            {
                "monoid": "sum",
                "budgetMode": "ub"
            }
        ]
    }
};
