// AUTO-GENERATED by scripts/sync-modules.js (auto-discovering)
// DO NOT EDIT MANUALLY
// Source of truth: ABA-variants/WABA

export const wabaModules = {
    core: {
        "base": `%% WABA Base Logic (Semiring/Monoid-Independent) - GROUNDING OPTIMIZED
%% This file contains the core argumentation logic that is independent
%% of the choice of semiring (weight propagation) and monoid (cost aggregation).
%%
%% OPTIMIZATIONS APPLIED:
%% - Added unary domain predicates to reduce grounding size
%% - Use rule/1 consistently instead of head(R,_)
%% - Removed redundant supported(X) joins

%% Budget constant used by the supported CLI wrapper and by raw clingo runs.
%% Framework files may also state budget(beta); duplicate identical facts are harmless.

%% ====================
%% DOMAIN PREDICATES
%% ====================
%% These unary predicates reduce grounding by avoiding repeated existential patterns

%% Rule meta-predicate (R is a rule identifier)
rule(R) :- head(R,_).

%% Unary flag: X appears as some rule head
is_head(X) :- head(_,X).

%% Unary flag: R has at least one body element
has_body(R) :- body(R,_).

%% Derived atoms: heads that are not assumptions
derived_atom(X) :- is_head(X), not assumption(X).

%% ====================
%% FLATNESS GUARD
%% ====================
%% WABA's weighted/budgeted semantics is defined for FLAT ABA frameworks: no
%% assumption may be the head of a rule. (The weight of an assumption is then
%% intrinsic, not extension-dependent; this matches the established ABA theory the
%% semantics rest on, and weighted non-flat ABA has no settled semantics.)
%% A non-flat assumption is flagged here and the framework is rejected outright,
%% rather than silently producing ill-defined weights.
non_flat_assumption(X) :- assumption(X), is_head(X).
:- non_flat_assumption(_).

%% ====================
%% CORE LOGIC
%% ====================

%% Support computation (weight-independent)
%% An atom is supported if:
%% 1. It's an assumption that is in, OR
%% 2. There exists a rule with this atom as head and all body elements are supported
supported(X) :- assumption(X), in(X).
supported(X) :- head(R,X), triggered_by_in(R).

%% A rule is triggered when all its body elements are supported
%% OPTIMIZED: Use rule(R) instead of head(R,_) for domain
triggered_by_in(R) :- rule(R), supported(X) : body(R,X).

%% Attack computation
%% An attack exists when a supported atom X attacks an assumption Y
%% (where Y's contrary is X), with the weight of X
%% OPTIMIZED: Remove redundant supported(X) check (supported_with_weight(X,W) implies support)
attacks_with_weight(X,Y,W) :- supported_with_weight(X,W), assumption(Y), contrary(Y,X).

%% Attack discretion choice
%% We can choose to discard any attack (at a cost)
{ discarded_attack(X,Y,W) : attacks_with_weight(X,Y,W) }.

%% Successful attacks
%% An attack succeeds if it's not discarded
attacks_successfully_with_weight(X,Y,W) :- attacks_with_weight(X,Y,W), not discarded_attack(X,Y,W).

%% ====================
%% BUDGET CONSTRAINT
%% ====================
%% Budget Constraints
%% ====================
%%
%% Budget value is typically set via command line: -c beta=N
budget(beta).

%% Budget constraints are in constraint/ directory.
%% \`constraint/ub.lp\` and \`constraint/lb.lp\` read the aggregate family from
%% the loaded monoid module.
%%
%% Load appropriate constraint file for budget enforcement:
%% - constraint/ub.lp - Upper bound for the active monoid family (cost ≤ beta)
%% - constraint/lb.lp - Lower bound for the active monoid family (cost ≥ beta)
%% - constraint/no_discard.lp - Plain ABA mode (no attack discarding)
`
    },
    semiring: {
        "arctic": `%% Arctic / max-plus semiring (additive family; negation-dual of tropical).
%% Semiring: (ℤ ∪ {-∞}, ⊕=max, ⊗=+, 0̄=#inf, 1̄=0) — strength polarity.
%% Conjunction = accumulate reward (sum); disjunction = strongest chain (max).
%% Weights are rewards/benefits, higher is better (longest path).

active_semiring(arctic).

oplus(max).
oplus_identity(#inf).
otimes_identity(0).
affordability_polarity(strength).

semiring_default_weight(legacy,0).
semiring_default_weight(aba,#sup).
semiring_default_weight(neutral,0).

%% Default weight policy selection for unweighted assumptions.
%%
%% Semiring modules provide semiring_default_weight(policy, value).
%% Callers may optionally load one explicit policy module from defaults/.
%% If none is loaded, legacy behavior is preserved.

configured_default_policy :- explicit_default_policy(_).

:- explicit_default_policy(P1), explicit_default_policy(P2), P1 != P2.

active_default_policy(P) :- explicit_default_policy(P).
active_default_policy(legacy) :- not configured_default_policy.

default_assumption_weight(W) :-
    active_default_policy(P),
    semiring_default_weight(P, W).

:- active_default_policy(P), not semiring_default_weight(P, _).

%% ============================================================================
%% _additive.lp — rule-body (⊗ = +) skeleton for the additive family
%% ============================================================================
%% Used by tropical (⊕=min, 0̄=#sup) and arctic (⊕=max, 0̄=#inf). ⊗ is fixed to
%% the integer sum.
%%
%% clingo #sum silently DROPS #sup and #inf, so the two infinities are handled
%% explicitly. For ⊗=+, the additive annihilator is the ⊕-identity 0̄ (x + 0̄ = 0̄):
%%   - any body element = 0̄ (annihilator)            -> result 0̄   (precedence)
%%   - else any body element = the opposite infinity  -> result that infinity
%%   - else                                            -> finite #sum

%% ============================================================================
%% _phase.lp — shared weight-propagation skeleton (algebra-agnostic part)
%% ============================================================================
%% Folds the support-phase and undefeated-phase weight propagations into ONE
%% parameterized computation pweight(Phase, X, W):
%%   support    : weights over the selected (in) atoms        -> supported_with_weight/2
%%   undefeated : weights over the not-defeated atoms         -> undefeated_weight/2
%%                (only populated when a defense semantics, e.g. semantics/admissible.lp,
%%                 defines derived_from_undefeated/1 + triggered_by_undefeated/1)
%%
%% A concrete algebra is fixed by a thin shim that declares:
%%   oplus(min|max)                       -- ⊕ combine of alternative derivations
%%   otimes_identity(I)                   -- 1̄ (empty-body / fact weight)
%%   affordability_polarity(strength|cost)
%% and includes a ⊗ skeleton (_idempotent.lp or _additive.lp) defining rule_deriv/4.

%% ---- phase bridges -----------------------------------------------------------
phase(support).
phase(undefeated).

phase_active(support, X)       :- supported(X).
phase_active(undefeated, X)    :- derived_from_undefeated(X).
phase_triggered(support, R)    :- triggered_by_in(R).
phase_triggered(undefeated, R) :- triggered_by_undefeated(R).
%% "selected" = the assumption is committed in this phase (in / not-defeated). The
%% undefeated form is gated by derived_from_undefeated, so the whole undefeated
%% phase is inert (no extra grounding) unless a defense semantics is loaded.
phase_selected(support, X)     :- in(X).
phase_selected(undefeated, X)  :- assumption(X), derived_from_undefeated(X).

%% ---- direct (own) weight: explicit weight, else policy default ---------------
%% Explicit weight is gated on phase_active (= in for flat assumptions, = supported
%% for non-flat / derived atoms — matches the previous per-semiring gating). The
%% policy default applies to unweighted assumptions that are selected.
direct_weight(P, X, V) :- phase(P), weight(X, V), phase_active(P, X).
direct_weight(P, X, V) :- phase(P), assumption(X), not weight(X, _), phase_selected(P, X), default_assumption_weight(V).

%% ---- assumptions: weight is just the direct weight --------------------------
%% WABA is restricted to flat ABA (see core/base.lp's flatness guard), so an
%% assumption is never a rule head — its weight is intrinsic, with no rule-derived
%% alternative to combine.
pweight(P, X, W) :- assumption(X), direct_weight(P, X, W).

%% ---- empty-body rule (fact) = empty conjunction = ⊗-identity 1̄ ---------------
%% Guarded by \`not weight(X,_)\` so an explicitly weighted fact keeps its weight.
rule_deriv(P, R, X, I) :-
    phase_active(P, X), rule(R), head(R, X), not has_body(R), not weight(X, _),
    otimes_identity(I).

%% ---- derived atoms: combine alternative derivations + explicit weight via ⊕ --
%% clingo #max keeps #sup / drops #inf and #min keeps #inf / drops #sup, which is
%% exactly the ⊕ identity (max-identity #inf, min-identity #sup), so no special
%% infinity handling is needed for the combine itself.
pweight(P, X, W) :-
    oplus(max), derived_atom(X), phase_active(P, X),
    W = #max{ V,R : rule_deriv(P,R,X,V) ; V : direct_weight(P,X,V) }.
pweight(P, X, W) :-
    oplus(min), derived_atom(X), phase_active(P, X),
    W = #min{ V,R : rule_deriv(P,R,X,V) ; V : direct_weight(P,X,V) }.

%% ---- expose the two phases under their conventional names --------------------
supported_with_weight(X, W) :- pweight(support, X, W).
undefeated_weight(X, W)     :- pweight(undefeated, X, W).

%% ---- attack affordability for defense semantics (polarity-parameterized) -----
unaffordable_attack(W, B) :- affordability_polarity(strength), undefeated_weight(_, W), budget(B), B = #sup, W != #sup.
unaffordable_attack(W, B) :- affordability_polarity(strength), undefeated_weight(_, W), budget(B), B = 0,     W != #inf.
unaffordable_attack(W, B) :- affordability_polarity(strength), undefeated_weight(_, W), budget(B), B != #sup, B != 0, W < B.
unaffordable_attack(W, B) :- affordability_polarity(cost),     undefeated_weight(_, W), budget(B), B = 0,     W != #inf.
unaffordable_attack(W, B) :- affordability_polarity(cost),     undefeated_weight(_, W), budget(B), B != 0,    W > B.


otimes_annihilator(A) :- oplus_identity(A).
opposite_infinity(#inf) :- oplus_identity(#sup).
opposite_infinity(#sup) :- oplus_identity(#inf).

add_body_has_annih(P, R) :- body(R, B), pweight(P, B, A), otimes_annihilator(A).
add_body_has_opp(P, R)   :- body(R, B), pweight(P, B, O), opposite_infinity(O).

%% Annihilator wins (a ⊗ 0̄ = 0̄).
rule_deriv(P, R, X, A) :-
    rule(R), head(R, X), has_body(R), phase_triggered(P, R),
    add_body_has_annih(P, R), otimes_annihilator(A).
%% No annihilator, but the opposite infinity saturates.
rule_deriv(P, R, X, O) :-
    rule(R), head(R, X), has_body(R), phase_triggered(P, R),
    not add_body_has_annih(P, R), add_body_has_opp(P, R), opposite_infinity(O).
%% Finite case: plain integer sum (no infinities present).
rule_deriv(P, R, X, W) :-
    rule(R), head(R, X), has_body(R), phase_triggered(P, R),
    not add_body_has_annih(P, R), not add_body_has_opp(P, R),
    W = #sum{ V,B : body(R,B), pweight(P,B,V) }.

`,
        "bottleneck_cost": `%% Bottleneck-cost semiring (idempotent family; order-dual of godel).
%% Semiring: (ℤ ∪ {±∞}, ⊕=min, ⊗=max, 0̄=#sup, 1̄=#inf) — cost polarity.
%% Conjunction = worst step (max); disjunction = cheapest alternative (min).
%% An argument costs as much as its single worst step (worst-case path).

active_semiring(bottleneck_cost).

oplus(min).
otimes(max).
oplus_identity(#sup).
otimes_identity(#inf).
affordability_polarity(cost).

semiring_default_weight(legacy,#inf).
semiring_default_weight(aba,#sup).
semiring_default_weight(neutral,#inf).

%% Default weight policy selection for unweighted assumptions.
%%
%% Semiring modules provide semiring_default_weight(policy, value).
%% Callers may optionally load one explicit policy module from defaults/.
%% If none is loaded, legacy behavior is preserved.

configured_default_policy :- explicit_default_policy(_).

:- explicit_default_policy(P1), explicit_default_policy(P2), P1 != P2.

active_default_policy(P) :- explicit_default_policy(P).
active_default_policy(legacy) :- not configured_default_policy.

default_assumption_weight(W) :-
    active_default_policy(P),
    semiring_default_weight(P, W).

:- active_default_policy(P), not semiring_default_weight(P, _).

%% ============================================================================
%% _idempotent.lp — rule-body (⊗) skeleton for the min/max family
%% ============================================================================
%% Used by godel (⊗=min, ⊕=max) and bottleneck_cost (⊗=max, ⊕=min), the two
%% bounded-distributive-lattice algebras. ⊗ is selected by otimes(min|max).
%%
%% No infinity guards are needed: clingo #min/#max drop the off-identity infinity
%% exactly as the lattice requires (#max drops #inf = max-identity; #min drops
%% #sup = min-identity), and keep the annihilating infinity (#max keeps #sup,
%% #min keeps #inf).

%% ============================================================================
%% _phase.lp — shared weight-propagation skeleton (algebra-agnostic part)
%% ============================================================================
%% Folds the support-phase and undefeated-phase weight propagations into ONE
%% parameterized computation pweight(Phase, X, W):
%%   support    : weights over the selected (in) atoms        -> supported_with_weight/2
%%   undefeated : weights over the not-defeated atoms         -> undefeated_weight/2
%%                (only populated when a defense semantics, e.g. semantics/admissible.lp,
%%                 defines derived_from_undefeated/1 + triggered_by_undefeated/1)
%%
%% A concrete algebra is fixed by a thin shim that declares:
%%   oplus(min|max)                       -- ⊕ combine of alternative derivations
%%   otimes_identity(I)                   -- 1̄ (empty-body / fact weight)
%%   affordability_polarity(strength|cost)
%% and includes a ⊗ skeleton (_idempotent.lp or _additive.lp) defining rule_deriv/4.

%% ---- phase bridges -----------------------------------------------------------
phase(support).
phase(undefeated).

phase_active(support, X)       :- supported(X).
phase_active(undefeated, X)    :- derived_from_undefeated(X).
phase_triggered(support, R)    :- triggered_by_in(R).
phase_triggered(undefeated, R) :- triggered_by_undefeated(R).
%% "selected" = the assumption is committed in this phase (in / not-defeated). The
%% undefeated form is gated by derived_from_undefeated, so the whole undefeated
%% phase is inert (no extra grounding) unless a defense semantics is loaded.
phase_selected(support, X)     :- in(X).
phase_selected(undefeated, X)  :- assumption(X), derived_from_undefeated(X).

%% ---- direct (own) weight: explicit weight, else policy default ---------------
%% Explicit weight is gated on phase_active (= in for flat assumptions, = supported
%% for non-flat / derived atoms — matches the previous per-semiring gating). The
%% policy default applies to unweighted assumptions that are selected.
direct_weight(P, X, V) :- phase(P), weight(X, V), phase_active(P, X).
direct_weight(P, X, V) :- phase(P), assumption(X), not weight(X, _), phase_selected(P, X), default_assumption_weight(V).

%% ---- assumptions: weight is just the direct weight --------------------------
%% WABA is restricted to flat ABA (see core/base.lp's flatness guard), so an
%% assumption is never a rule head — its weight is intrinsic, with no rule-derived
%% alternative to combine.
pweight(P, X, W) :- assumption(X), direct_weight(P, X, W).

%% ---- empty-body rule (fact) = empty conjunction = ⊗-identity 1̄ ---------------
%% Guarded by \`not weight(X,_)\` so an explicitly weighted fact keeps its weight.
rule_deriv(P, R, X, I) :-
    phase_active(P, X), rule(R), head(R, X), not has_body(R), not weight(X, _),
    otimes_identity(I).

%% ---- derived atoms: combine alternative derivations + explicit weight via ⊕ --
%% clingo #max keeps #sup / drops #inf and #min keeps #inf / drops #sup, which is
%% exactly the ⊕ identity (max-identity #inf, min-identity #sup), so no special
%% infinity handling is needed for the combine itself.
pweight(P, X, W) :-
    oplus(max), derived_atom(X), phase_active(P, X),
    W = #max{ V,R : rule_deriv(P,R,X,V) ; V : direct_weight(P,X,V) }.
pweight(P, X, W) :-
    oplus(min), derived_atom(X), phase_active(P, X),
    W = #min{ V,R : rule_deriv(P,R,X,V) ; V : direct_weight(P,X,V) }.

%% ---- expose the two phases under their conventional names --------------------
supported_with_weight(X, W) :- pweight(support, X, W).
undefeated_weight(X, W)     :- pweight(undefeated, X, W).

%% ---- attack affordability for defense semantics (polarity-parameterized) -----
unaffordable_attack(W, B) :- affordability_polarity(strength), undefeated_weight(_, W), budget(B), B = #sup, W != #sup.
unaffordable_attack(W, B) :- affordability_polarity(strength), undefeated_weight(_, W), budget(B), B = 0,     W != #inf.
unaffordable_attack(W, B) :- affordability_polarity(strength), undefeated_weight(_, W), budget(B), B != #sup, B != 0, W < B.
unaffordable_attack(W, B) :- affordability_polarity(cost),     undefeated_weight(_, W), budget(B), B = 0,     W != #inf.
unaffordable_attack(W, B) :- affordability_polarity(cost),     undefeated_weight(_, W), budget(B), B != 0,    W > B.


rule_deriv(P, R, X, W) :-
    otimes(min), rule(R), head(R, X), has_body(R), phase_triggered(P, R),
    W = #min{ V,B : body(R,B), pweight(P,B,V) }.

rule_deriv(P, R, X, W) :-
    otimes(max), rule(R), head(R, X), has_body(R), phase_triggered(P, R),
    W = #max{ V,B : body(R,B), pweight(P,B,V) }.

`,
        "godel": `%% Gödel / Fuzzy semiring (idempotent family).
%% Semiring: (ℤ ∪ {±∞}, ⊕=max, ⊗=min, 0̄=#inf, 1̄=#sup) — strength polarity.
%% Conjunction = weakest link (min); disjunction = strongest alternative (max).
%% Weights are truth degrees / confidences, higher is better (original WABA).

active_semiring(godel).

oplus(max).
otimes(min).
oplus_identity(#inf).
otimes_identity(#sup).
affordability_polarity(strength).

semiring_default_weight(legacy,#sup).
semiring_default_weight(aba,#sup).
semiring_default_weight(neutral,#sup).

%% Default weight policy selection for unweighted assumptions.
%%
%% Semiring modules provide semiring_default_weight(policy, value).
%% Callers may optionally load one explicit policy module from defaults/.
%% If none is loaded, legacy behavior is preserved.

configured_default_policy :- explicit_default_policy(_).

:- explicit_default_policy(P1), explicit_default_policy(P2), P1 != P2.

active_default_policy(P) :- explicit_default_policy(P).
active_default_policy(legacy) :- not configured_default_policy.

default_assumption_weight(W) :-
    active_default_policy(P),
    semiring_default_weight(P, W).

:- active_default_policy(P), not semiring_default_weight(P, _).

%% ============================================================================
%% _idempotent.lp — rule-body (⊗) skeleton for the min/max family
%% ============================================================================
%% Used by godel (⊗=min, ⊕=max) and bottleneck_cost (⊗=max, ⊕=min), the two
%% bounded-distributive-lattice algebras. ⊗ is selected by otimes(min|max).
%%
%% No infinity guards are needed: clingo #min/#max drop the off-identity infinity
%% exactly as the lattice requires (#max drops #inf = max-identity; #min drops
%% #sup = min-identity), and keep the annihilating infinity (#max keeps #sup,
%% #min keeps #inf).

%% ============================================================================
%% _phase.lp — shared weight-propagation skeleton (algebra-agnostic part)
%% ============================================================================
%% Folds the support-phase and undefeated-phase weight propagations into ONE
%% parameterized computation pweight(Phase, X, W):
%%   support    : weights over the selected (in) atoms        -> supported_with_weight/2
%%   undefeated : weights over the not-defeated atoms         -> undefeated_weight/2
%%                (only populated when a defense semantics, e.g. semantics/admissible.lp,
%%                 defines derived_from_undefeated/1 + triggered_by_undefeated/1)
%%
%% A concrete algebra is fixed by a thin shim that declares:
%%   oplus(min|max)                       -- ⊕ combine of alternative derivations
%%   otimes_identity(I)                   -- 1̄ (empty-body / fact weight)
%%   affordability_polarity(strength|cost)
%% and includes a ⊗ skeleton (_idempotent.lp or _additive.lp) defining rule_deriv/4.

%% ---- phase bridges -----------------------------------------------------------
phase(support).
phase(undefeated).

phase_active(support, X)       :- supported(X).
phase_active(undefeated, X)    :- derived_from_undefeated(X).
phase_triggered(support, R)    :- triggered_by_in(R).
phase_triggered(undefeated, R) :- triggered_by_undefeated(R).
%% "selected" = the assumption is committed in this phase (in / not-defeated). The
%% undefeated form is gated by derived_from_undefeated, so the whole undefeated
%% phase is inert (no extra grounding) unless a defense semantics is loaded.
phase_selected(support, X)     :- in(X).
phase_selected(undefeated, X)  :- assumption(X), derived_from_undefeated(X).

%% ---- direct (own) weight: explicit weight, else policy default ---------------
%% Explicit weight is gated on phase_active (= in for flat assumptions, = supported
%% for non-flat / derived atoms — matches the previous per-semiring gating). The
%% policy default applies to unweighted assumptions that are selected.
direct_weight(P, X, V) :- phase(P), weight(X, V), phase_active(P, X).
direct_weight(P, X, V) :- phase(P), assumption(X), not weight(X, _), phase_selected(P, X), default_assumption_weight(V).

%% ---- assumptions: weight is just the direct weight --------------------------
%% WABA is restricted to flat ABA (see core/base.lp's flatness guard), so an
%% assumption is never a rule head — its weight is intrinsic, with no rule-derived
%% alternative to combine.
pweight(P, X, W) :- assumption(X), direct_weight(P, X, W).

%% ---- empty-body rule (fact) = empty conjunction = ⊗-identity 1̄ ---------------
%% Guarded by \`not weight(X,_)\` so an explicitly weighted fact keeps its weight.
rule_deriv(P, R, X, I) :-
    phase_active(P, X), rule(R), head(R, X), not has_body(R), not weight(X, _),
    otimes_identity(I).

%% ---- derived atoms: combine alternative derivations + explicit weight via ⊕ --
%% clingo #max keeps #sup / drops #inf and #min keeps #inf / drops #sup, which is
%% exactly the ⊕ identity (max-identity #inf, min-identity #sup), so no special
%% infinity handling is needed for the combine itself.
pweight(P, X, W) :-
    oplus(max), derived_atom(X), phase_active(P, X),
    W = #max{ V,R : rule_deriv(P,R,X,V) ; V : direct_weight(P,X,V) }.
pweight(P, X, W) :-
    oplus(min), derived_atom(X), phase_active(P, X),
    W = #min{ V,R : rule_deriv(P,R,X,V) ; V : direct_weight(P,X,V) }.

%% ---- expose the two phases under their conventional names --------------------
supported_with_weight(X, W) :- pweight(support, X, W).
undefeated_weight(X, W)     :- pweight(undefeated, X, W).

%% ---- attack affordability for defense semantics (polarity-parameterized) -----
unaffordable_attack(W, B) :- affordability_polarity(strength), undefeated_weight(_, W), budget(B), B = #sup, W != #sup.
unaffordable_attack(W, B) :- affordability_polarity(strength), undefeated_weight(_, W), budget(B), B = 0,     W != #inf.
unaffordable_attack(W, B) :- affordability_polarity(strength), undefeated_weight(_, W), budget(B), B != #sup, B != 0, W < B.
unaffordable_attack(W, B) :- affordability_polarity(cost),     undefeated_weight(_, W), budget(B), B = 0,     W != #inf.
unaffordable_attack(W, B) :- affordability_polarity(cost),     undefeated_weight(_, W), budget(B), B != 0,    W > B.


rule_deriv(P, R, X, W) :-
    otimes(min), rule(R), head(R, X), has_body(R), phase_triggered(P, R),
    W = #min{ V,B : body(R,B), pweight(P,B,V) }.

rule_deriv(P, R, X, W) :-
    otimes(max), rule(R), head(R, X), has_body(R), phase_triggered(P, R),
    W = #max{ V,B : body(R,B), pweight(P,B,V) }.

`,
        "godel_low": `%% ALIAS — not a separate algebra.
%% \`godel_low\` is the lower-is-better (cost) polarity dual of \`godel\` (max,min).
%% That dual is exactly the (min, max) bottleneck-cost algebra, so this file is a
%% thin alias for semiring/bottleneck_cost.lp. Kept so that \`--semiring godel_low\`
%% and raw \`clingo ... semiring/godel_low.lp ...\` runs keep resolving.
%% Bottleneck-cost semiring (idempotent family; order-dual of godel).
%% Semiring: (ℤ ∪ {±∞}, ⊕=min, ⊗=max, 0̄=#sup, 1̄=#inf) — cost polarity.
%% Conjunction = worst step (max); disjunction = cheapest alternative (min).
%% An argument costs as much as its single worst step (worst-case path).

active_semiring(bottleneck_cost).

oplus(min).
otimes(max).
oplus_identity(#sup).
otimes_identity(#inf).
affordability_polarity(cost).

semiring_default_weight(legacy,#inf).
semiring_default_weight(aba,#sup).
semiring_default_weight(neutral,#inf).

%% Default weight policy selection for unweighted assumptions.
%%
%% Semiring modules provide semiring_default_weight(policy, value).
%% Callers may optionally load one explicit policy module from defaults/.
%% If none is loaded, legacy behavior is preserved.

configured_default_policy :- explicit_default_policy(_).

:- explicit_default_policy(P1), explicit_default_policy(P2), P1 != P2.

active_default_policy(P) :- explicit_default_policy(P).
active_default_policy(legacy) :- not configured_default_policy.

default_assumption_weight(W) :-
    active_default_policy(P),
    semiring_default_weight(P, W).

:- active_default_policy(P), not semiring_default_weight(P, _).

%% ============================================================================
%% _idempotent.lp — rule-body (⊗) skeleton for the min/max family
%% ============================================================================
%% Used by godel (⊗=min, ⊕=max) and bottleneck_cost (⊗=max, ⊕=min), the two
%% bounded-distributive-lattice algebras. ⊗ is selected by otimes(min|max).
%%
%% No infinity guards are needed: clingo #min/#max drop the off-identity infinity
%% exactly as the lattice requires (#max drops #inf = max-identity; #min drops
%% #sup = min-identity), and keep the annihilating infinity (#max keeps #sup,
%% #min keeps #inf).

%% ============================================================================
%% _phase.lp — shared weight-propagation skeleton (algebra-agnostic part)
%% ============================================================================
%% Folds the support-phase and undefeated-phase weight propagations into ONE
%% parameterized computation pweight(Phase, X, W):
%%   support    : weights over the selected (in) atoms        -> supported_with_weight/2
%%   undefeated : weights over the not-defeated atoms         -> undefeated_weight/2
%%                (only populated when a defense semantics, e.g. semantics/admissible.lp,
%%                 defines derived_from_undefeated/1 + triggered_by_undefeated/1)
%%
%% A concrete algebra is fixed by a thin shim that declares:
%%   oplus(min|max)                       -- ⊕ combine of alternative derivations
%%   otimes_identity(I)                   -- 1̄ (empty-body / fact weight)
%%   affordability_polarity(strength|cost)
%% and includes a ⊗ skeleton (_idempotent.lp or _additive.lp) defining rule_deriv/4.

%% ---- phase bridges -----------------------------------------------------------
phase(support).
phase(undefeated).

phase_active(support, X)       :- supported(X).
phase_active(undefeated, X)    :- derived_from_undefeated(X).
phase_triggered(support, R)    :- triggered_by_in(R).
phase_triggered(undefeated, R) :- triggered_by_undefeated(R).
%% "selected" = the assumption is committed in this phase (in / not-defeated). The
%% undefeated form is gated by derived_from_undefeated, so the whole undefeated
%% phase is inert (no extra grounding) unless a defense semantics is loaded.
phase_selected(support, X)     :- in(X).
phase_selected(undefeated, X)  :- assumption(X), derived_from_undefeated(X).

%% ---- direct (own) weight: explicit weight, else policy default ---------------
%% Explicit weight is gated on phase_active (= in for flat assumptions, = supported
%% for non-flat / derived atoms — matches the previous per-semiring gating). The
%% policy default applies to unweighted assumptions that are selected.
direct_weight(P, X, V) :- phase(P), weight(X, V), phase_active(P, X).
direct_weight(P, X, V) :- phase(P), assumption(X), not weight(X, _), phase_selected(P, X), default_assumption_weight(V).

%% ---- assumptions: weight is just the direct weight --------------------------
%% WABA is restricted to flat ABA (see core/base.lp's flatness guard), so an
%% assumption is never a rule head — its weight is intrinsic, with no rule-derived
%% alternative to combine.
pweight(P, X, W) :- assumption(X), direct_weight(P, X, W).

%% ---- empty-body rule (fact) = empty conjunction = ⊗-identity 1̄ ---------------
%% Guarded by \`not weight(X,_)\` so an explicitly weighted fact keeps its weight.
rule_deriv(P, R, X, I) :-
    phase_active(P, X), rule(R), head(R, X), not has_body(R), not weight(X, _),
    otimes_identity(I).

%% ---- derived atoms: combine alternative derivations + explicit weight via ⊕ --
%% clingo #max keeps #sup / drops #inf and #min keeps #inf / drops #sup, which is
%% exactly the ⊕ identity (max-identity #inf, min-identity #sup), so no special
%% infinity handling is needed for the combine itself.
pweight(P, X, W) :-
    oplus(max), derived_atom(X), phase_active(P, X),
    W = #max{ V,R : rule_deriv(P,R,X,V) ; V : direct_weight(P,X,V) }.
pweight(P, X, W) :-
    oplus(min), derived_atom(X), phase_active(P, X),
    W = #min{ V,R : rule_deriv(P,R,X,V) ; V : direct_weight(P,X,V) }.

%% ---- expose the two phases under their conventional names --------------------
supported_with_weight(X, W) :- pweight(support, X, W).
undefeated_weight(X, W)     :- pweight(undefeated, X, W).

%% ---- attack affordability for defense semantics (polarity-parameterized) -----
unaffordable_attack(W, B) :- affordability_polarity(strength), undefeated_weight(_, W), budget(B), B = #sup, W != #sup.
unaffordable_attack(W, B) :- affordability_polarity(strength), undefeated_weight(_, W), budget(B), B = 0,     W != #inf.
unaffordable_attack(W, B) :- affordability_polarity(strength), undefeated_weight(_, W), budget(B), B != #sup, B != 0, W < B.
unaffordable_attack(W, B) :- affordability_polarity(cost),     undefeated_weight(_, W), budget(B), B = 0,     W != #inf.
unaffordable_attack(W, B) :- affordability_polarity(cost),     undefeated_weight(_, W), budget(B), B != 0,    W > B.


rule_deriv(P, R, X, W) :-
    otimes(min), rule(R), head(R, X), has_body(R), phase_triggered(P, R),
    W = #min{ V,B : body(R,B), pweight(P,B,V) }.

rule_deriv(P, R, X, W) :-
    otimes(max), rule(R), head(R, X), has_body(R), phase_triggered(P, R),
    W = #max{ V,B : body(R,B), pweight(P,B,V) }.


`,
        "lukasiewicz": `%% Łukasiewicz / bounded-sum semiring (outside the godel/tropical 2×2).
%% Semiring: ({0..k}, ⊕=max, ⊗=max(0, a+b-k), 0̄=0, 1̄=k) — strength polarity.
%% n-ary ⊗: max(0, (Σ wi) - (n-1)*k). Unlike Gödel's weakest-link, a chain of weak
%% premises ERODES certainty toward 0. The only ⊗ that is not min, max or plain +,
%% so it shares _phase.lp's propagation skeleton but supplies its own rule_deriv/4.
%% Weights live on the integer grid {0..k} (#const k, default 1000); override -c k=N.

#const k = 1000.

active_semiring(lukasiewicz).

oplus(max).
oplus_identity(0).
otimes_identity(k).
affordability_polarity(strength).

semiring_default_weight(legacy,k).
semiring_default_weight(aba,k).
semiring_default_weight(neutral,k).

%% Default weight policy selection for unweighted assumptions.
%%
%% Semiring modules provide semiring_default_weight(policy, value).
%% Callers may optionally load one explicit policy module from defaults/.
%% If none is loaded, legacy behavior is preserved.

configured_default_policy :- explicit_default_policy(_).

:- explicit_default_policy(P1), explicit_default_policy(P2), P1 != P2.

active_default_policy(P) :- explicit_default_policy(P).
active_default_policy(legacy) :- not configured_default_policy.

default_assumption_weight(W) :-
    active_default_policy(P),
    semiring_default_weight(P, W).

:- active_default_policy(P), not semiring_default_weight(P, _).

%% ============================================================================
%% _phase.lp — shared weight-propagation skeleton (algebra-agnostic part)
%% ============================================================================
%% Folds the support-phase and undefeated-phase weight propagations into ONE
%% parameterized computation pweight(Phase, X, W):
%%   support    : weights over the selected (in) atoms        -> supported_with_weight/2
%%   undefeated : weights over the not-defeated atoms         -> undefeated_weight/2
%%                (only populated when a defense semantics, e.g. semantics/admissible.lp,
%%                 defines derived_from_undefeated/1 + triggered_by_undefeated/1)
%%
%% A concrete algebra is fixed by a thin shim that declares:
%%   oplus(min|max)                       -- ⊕ combine of alternative derivations
%%   otimes_identity(I)                   -- 1̄ (empty-body / fact weight)
%%   affordability_polarity(strength|cost)
%% and includes a ⊗ skeleton (_idempotent.lp or _additive.lp) defining rule_deriv/4.

%% ---- phase bridges -----------------------------------------------------------
phase(support).
phase(undefeated).

phase_active(support, X)       :- supported(X).
phase_active(undefeated, X)    :- derived_from_undefeated(X).
phase_triggered(support, R)    :- triggered_by_in(R).
phase_triggered(undefeated, R) :- triggered_by_undefeated(R).
%% "selected" = the assumption is committed in this phase (in / not-defeated). The
%% undefeated form is gated by derived_from_undefeated, so the whole undefeated
%% phase is inert (no extra grounding) unless a defense semantics is loaded.
phase_selected(support, X)     :- in(X).
phase_selected(undefeated, X)  :- assumption(X), derived_from_undefeated(X).

%% ---- direct (own) weight: explicit weight, else policy default ---------------
%% Explicit weight is gated on phase_active (= in for flat assumptions, = supported
%% for non-flat / derived atoms — matches the previous per-semiring gating). The
%% policy default applies to unweighted assumptions that are selected.
direct_weight(P, X, V) :- phase(P), weight(X, V), phase_active(P, X).
direct_weight(P, X, V) :- phase(P), assumption(X), not weight(X, _), phase_selected(P, X), default_assumption_weight(V).

%% ---- assumptions: weight is just the direct weight --------------------------
%% WABA is restricted to flat ABA (see core/base.lp's flatness guard), so an
%% assumption is never a rule head — its weight is intrinsic, with no rule-derived
%% alternative to combine.
pweight(P, X, W) :- assumption(X), direct_weight(P, X, W).

%% ---- empty-body rule (fact) = empty conjunction = ⊗-identity 1̄ ---------------
%% Guarded by \`not weight(X,_)\` so an explicitly weighted fact keeps its weight.
rule_deriv(P, R, X, I) :-
    phase_active(P, X), rule(R), head(R, X), not has_body(R), not weight(X, _),
    otimes_identity(I).

%% ---- derived atoms: combine alternative derivations + explicit weight via ⊕ --
%% clingo #max keeps #sup / drops #inf and #min keeps #inf / drops #sup, which is
%% exactly the ⊕ identity (max-identity #inf, min-identity #sup), so no special
%% infinity handling is needed for the combine itself.
pweight(P, X, W) :-
    oplus(max), derived_atom(X), phase_active(P, X),
    W = #max{ V,R : rule_deriv(P,R,X,V) ; V : direct_weight(P,X,V) }.
pweight(P, X, W) :-
    oplus(min), derived_atom(X), phase_active(P, X),
    W = #min{ V,R : rule_deriv(P,R,X,V) ; V : direct_weight(P,X,V) }.

%% ---- expose the two phases under their conventional names --------------------
supported_with_weight(X, W) :- pweight(support, X, W).
undefeated_weight(X, W)     :- pweight(undefeated, X, W).

%% ---- attack affordability for defense semantics (polarity-parameterized) -----
unaffordable_attack(W, B) :- affordability_polarity(strength), undefeated_weight(_, W), budget(B), B = #sup, W != #sup.
unaffordable_attack(W, B) :- affordability_polarity(strength), undefeated_weight(_, W), budget(B), B = 0,     W != #inf.
unaffordable_attack(W, B) :- affordability_polarity(strength), undefeated_weight(_, W), budget(B), B != #sup, B != 0, W < B.
unaffordable_attack(W, B) :- affordability_polarity(cost),     undefeated_weight(_, W), budget(B), B = 0,     W != #inf.
unaffordable_attack(W, B) :- affordability_polarity(cost),     undefeated_weight(_, W), budget(B), B != 0,    W > B.


%% Bounded-sum ⊗ (both phases). #sum drops #sup/#inf, so saturate them first:
%% #inf -> 0 (the bounded-sum annihilator, precedence), #sup -> k (grid top).
luk_body_has_sup(P, R) :- body(R, B), pweight(P, B, #sup).
luk_body_has_inf(P, R) :- body(R, B), pweight(P, B, #inf).

rule_deriv(P, R, X, 0) :-
    rule(R), head(R, X), has_body(R), phase_triggered(P, R),
    luk_body_has_inf(P, R).
rule_deriv(P, R, X, k) :-
    rule(R), head(R, X), has_body(R), phase_triggered(P, R),
    not luk_body_has_inf(P, R), luk_body_has_sup(P, R).
rule_deriv(P, R, X, M) :-
    rule(R), head(R, X), has_body(R), phase_triggered(P, R),
    not luk_body_has_inf(P, R), not luk_body_has_sup(P, R),
    S = #sum{ V,B : body(R,B), pweight(P,B,V) },
    N = #count{ B : body(R,B) },
    M = #max{ 0 ; S-(N-1)*k }.
`,
        "tropical": `%% Tropical / min-plus semiring (additive family).
%% Semiring: (ℤ ∪ {+∞}, ⊕=min, ⊗=+, 0̄=#sup, 1̄=0) — cost polarity.
%% Conjunction = accumulate cost (sum); disjunction = cheapest proof (min).
%% Weights are costs, lower is better (shortest path).

active_semiring(tropical).

oplus(min).
oplus_identity(#sup).
otimes_identity(0).
affordability_polarity(cost).

semiring_default_weight(legacy,#sup).
semiring_default_weight(aba,#sup).
semiring_default_weight(neutral,0).

%% Default weight policy selection for unweighted assumptions.
%%
%% Semiring modules provide semiring_default_weight(policy, value).
%% Callers may optionally load one explicit policy module from defaults/.
%% If none is loaded, legacy behavior is preserved.

configured_default_policy :- explicit_default_policy(_).

:- explicit_default_policy(P1), explicit_default_policy(P2), P1 != P2.

active_default_policy(P) :- explicit_default_policy(P).
active_default_policy(legacy) :- not configured_default_policy.

default_assumption_weight(W) :-
    active_default_policy(P),
    semiring_default_weight(P, W).

:- active_default_policy(P), not semiring_default_weight(P, _).

%% ============================================================================
%% _additive.lp — rule-body (⊗ = +) skeleton for the additive family
%% ============================================================================
%% Used by tropical (⊕=min, 0̄=#sup) and arctic (⊕=max, 0̄=#inf). ⊗ is fixed to
%% the integer sum.
%%
%% clingo #sum silently DROPS #sup and #inf, so the two infinities are handled
%% explicitly. For ⊗=+, the additive annihilator is the ⊕-identity 0̄ (x + 0̄ = 0̄):
%%   - any body element = 0̄ (annihilator)            -> result 0̄   (precedence)
%%   - else any body element = the opposite infinity  -> result that infinity
%%   - else                                            -> finite #sum

%% ============================================================================
%% _phase.lp — shared weight-propagation skeleton (algebra-agnostic part)
%% ============================================================================
%% Folds the support-phase and undefeated-phase weight propagations into ONE
%% parameterized computation pweight(Phase, X, W):
%%   support    : weights over the selected (in) atoms        -> supported_with_weight/2
%%   undefeated : weights over the not-defeated atoms         -> undefeated_weight/2
%%                (only populated when a defense semantics, e.g. semantics/admissible.lp,
%%                 defines derived_from_undefeated/1 + triggered_by_undefeated/1)
%%
%% A concrete algebra is fixed by a thin shim that declares:
%%   oplus(min|max)                       -- ⊕ combine of alternative derivations
%%   otimes_identity(I)                   -- 1̄ (empty-body / fact weight)
%%   affordability_polarity(strength|cost)
%% and includes a ⊗ skeleton (_idempotent.lp or _additive.lp) defining rule_deriv/4.

%% ---- phase bridges -----------------------------------------------------------
phase(support).
phase(undefeated).

phase_active(support, X)       :- supported(X).
phase_active(undefeated, X)    :- derived_from_undefeated(X).
phase_triggered(support, R)    :- triggered_by_in(R).
phase_triggered(undefeated, R) :- triggered_by_undefeated(R).
%% "selected" = the assumption is committed in this phase (in / not-defeated). The
%% undefeated form is gated by derived_from_undefeated, so the whole undefeated
%% phase is inert (no extra grounding) unless a defense semantics is loaded.
phase_selected(support, X)     :- in(X).
phase_selected(undefeated, X)  :- assumption(X), derived_from_undefeated(X).

%% ---- direct (own) weight: explicit weight, else policy default ---------------
%% Explicit weight is gated on phase_active (= in for flat assumptions, = supported
%% for non-flat / derived atoms — matches the previous per-semiring gating). The
%% policy default applies to unweighted assumptions that are selected.
direct_weight(P, X, V) :- phase(P), weight(X, V), phase_active(P, X).
direct_weight(P, X, V) :- phase(P), assumption(X), not weight(X, _), phase_selected(P, X), default_assumption_weight(V).

%% ---- assumptions: weight is just the direct weight --------------------------
%% WABA is restricted to flat ABA (see core/base.lp's flatness guard), so an
%% assumption is never a rule head — its weight is intrinsic, with no rule-derived
%% alternative to combine.
pweight(P, X, W) :- assumption(X), direct_weight(P, X, W).

%% ---- empty-body rule (fact) = empty conjunction = ⊗-identity 1̄ ---------------
%% Guarded by \`not weight(X,_)\` so an explicitly weighted fact keeps its weight.
rule_deriv(P, R, X, I) :-
    phase_active(P, X), rule(R), head(R, X), not has_body(R), not weight(X, _),
    otimes_identity(I).

%% ---- derived atoms: combine alternative derivations + explicit weight via ⊕ --
%% clingo #max keeps #sup / drops #inf and #min keeps #inf / drops #sup, which is
%% exactly the ⊕ identity (max-identity #inf, min-identity #sup), so no special
%% infinity handling is needed for the combine itself.
pweight(P, X, W) :-
    oplus(max), derived_atom(X), phase_active(P, X),
    W = #max{ V,R : rule_deriv(P,R,X,V) ; V : direct_weight(P,X,V) }.
pweight(P, X, W) :-
    oplus(min), derived_atom(X), phase_active(P, X),
    W = #min{ V,R : rule_deriv(P,R,X,V) ; V : direct_weight(P,X,V) }.

%% ---- expose the two phases under their conventional names --------------------
supported_with_weight(X, W) :- pweight(support, X, W).
undefeated_weight(X, W)     :- pweight(undefeated, X, W).

%% ---- attack affordability for defense semantics (polarity-parameterized) -----
unaffordable_attack(W, B) :- affordability_polarity(strength), undefeated_weight(_, W), budget(B), B = #sup, W != #sup.
unaffordable_attack(W, B) :- affordability_polarity(strength), undefeated_weight(_, W), budget(B), B = 0,     W != #inf.
unaffordable_attack(W, B) :- affordability_polarity(strength), undefeated_weight(_, W), budget(B), B != #sup, B != 0, W < B.
unaffordable_attack(W, B) :- affordability_polarity(cost),     undefeated_weight(_, W), budget(B), B = 0,     W != #inf.
unaffordable_attack(W, B) :- affordability_polarity(cost),     undefeated_weight(_, W), budget(B), B != 0,    W > B.


otimes_annihilator(A) :- oplus_identity(A).
opposite_infinity(#inf) :- oplus_identity(#sup).
opposite_infinity(#sup) :- oplus_identity(#inf).

add_body_has_annih(P, R) :- body(R, B), pweight(P, B, A), otimes_annihilator(A).
add_body_has_opp(P, R)   :- body(R, B), pweight(P, B, O), opposite_infinity(O).

%% Annihilator wins (a ⊗ 0̄ = 0̄).
rule_deriv(P, R, X, A) :-
    rule(R), head(R, X), has_body(R), phase_triggered(P, R),
    add_body_has_annih(P, R), otimes_annihilator(A).
%% No annihilator, but the opposite infinity saturates.
rule_deriv(P, R, X, O) :-
    rule(R), head(R, X), has_body(R), phase_triggered(P, R),
    not add_body_has_annih(P, R), add_body_has_opp(P, R), opposite_infinity(O).
%% Finite case: plain integer sum (no infinities present).
rule_deriv(P, R, X, W) :-
    rule(R), head(R, X), has_body(R), phase_triggered(P, R),
    not add_body_has_annih(P, R), not add_body_has_opp(P, R),
    W = #sum{ V,B : body(R,B), pweight(P,B,V) }.

`,
        "tropical_high": `%% ALIAS — not a separate algebra.
%% \`tropical_high\` is the higher-is-better (reward) polarity dual of \`tropical\` (min,+).
%% That dual is exactly the (max, +) arctic algebra, so this file is a thin alias for
%% semiring/arctic.lp. Kept so that \`--semiring tropical_high\` and raw
%% \`clingo ... semiring/tropical_high.lp ...\` runs keep resolving.
%% Arctic / max-plus semiring (additive family; negation-dual of tropical).
%% Semiring: (ℤ ∪ {-∞}, ⊕=max, ⊗=+, 0̄=#inf, 1̄=0) — strength polarity.
%% Conjunction = accumulate reward (sum); disjunction = strongest chain (max).
%% Weights are rewards/benefits, higher is better (longest path).

active_semiring(arctic).

oplus(max).
oplus_identity(#inf).
otimes_identity(0).
affordability_polarity(strength).

semiring_default_weight(legacy,0).
semiring_default_weight(aba,#sup).
semiring_default_weight(neutral,0).

%% Default weight policy selection for unweighted assumptions.
%%
%% Semiring modules provide semiring_default_weight(policy, value).
%% Callers may optionally load one explicit policy module from defaults/.
%% If none is loaded, legacy behavior is preserved.

configured_default_policy :- explicit_default_policy(_).

:- explicit_default_policy(P1), explicit_default_policy(P2), P1 != P2.

active_default_policy(P) :- explicit_default_policy(P).
active_default_policy(legacy) :- not configured_default_policy.

default_assumption_weight(W) :-
    active_default_policy(P),
    semiring_default_weight(P, W).

:- active_default_policy(P), not semiring_default_weight(P, _).

%% ============================================================================
%% _additive.lp — rule-body (⊗ = +) skeleton for the additive family
%% ============================================================================
%% Used by tropical (⊕=min, 0̄=#sup) and arctic (⊕=max, 0̄=#inf). ⊗ is fixed to
%% the integer sum.
%%
%% clingo #sum silently DROPS #sup and #inf, so the two infinities are handled
%% explicitly. For ⊗=+, the additive annihilator is the ⊕-identity 0̄ (x + 0̄ = 0̄):
%%   - any body element = 0̄ (annihilator)            -> result 0̄   (precedence)
%%   - else any body element = the opposite infinity  -> result that infinity
%%   - else                                            -> finite #sum

%% ============================================================================
%% _phase.lp — shared weight-propagation skeleton (algebra-agnostic part)
%% ============================================================================
%% Folds the support-phase and undefeated-phase weight propagations into ONE
%% parameterized computation pweight(Phase, X, W):
%%   support    : weights over the selected (in) atoms        -> supported_with_weight/2
%%   undefeated : weights over the not-defeated atoms         -> undefeated_weight/2
%%                (only populated when a defense semantics, e.g. semantics/admissible.lp,
%%                 defines derived_from_undefeated/1 + triggered_by_undefeated/1)
%%
%% A concrete algebra is fixed by a thin shim that declares:
%%   oplus(min|max)                       -- ⊕ combine of alternative derivations
%%   otimes_identity(I)                   -- 1̄ (empty-body / fact weight)
%%   affordability_polarity(strength|cost)
%% and includes a ⊗ skeleton (_idempotent.lp or _additive.lp) defining rule_deriv/4.

%% ---- phase bridges -----------------------------------------------------------
phase(support).
phase(undefeated).

phase_active(support, X)       :- supported(X).
phase_active(undefeated, X)    :- derived_from_undefeated(X).
phase_triggered(support, R)    :- triggered_by_in(R).
phase_triggered(undefeated, R) :- triggered_by_undefeated(R).
%% "selected" = the assumption is committed in this phase (in / not-defeated). The
%% undefeated form is gated by derived_from_undefeated, so the whole undefeated
%% phase is inert (no extra grounding) unless a defense semantics is loaded.
phase_selected(support, X)     :- in(X).
phase_selected(undefeated, X)  :- assumption(X), derived_from_undefeated(X).

%% ---- direct (own) weight: explicit weight, else policy default ---------------
%% Explicit weight is gated on phase_active (= in for flat assumptions, = supported
%% for non-flat / derived atoms — matches the previous per-semiring gating). The
%% policy default applies to unweighted assumptions that are selected.
direct_weight(P, X, V) :- phase(P), weight(X, V), phase_active(P, X).
direct_weight(P, X, V) :- phase(P), assumption(X), not weight(X, _), phase_selected(P, X), default_assumption_weight(V).

%% ---- assumptions: weight is just the direct weight --------------------------
%% WABA is restricted to flat ABA (see core/base.lp's flatness guard), so an
%% assumption is never a rule head — its weight is intrinsic, with no rule-derived
%% alternative to combine.
pweight(P, X, W) :- assumption(X), direct_weight(P, X, W).

%% ---- empty-body rule (fact) = empty conjunction = ⊗-identity 1̄ ---------------
%% Guarded by \`not weight(X,_)\` so an explicitly weighted fact keeps its weight.
rule_deriv(P, R, X, I) :-
    phase_active(P, X), rule(R), head(R, X), not has_body(R), not weight(X, _),
    otimes_identity(I).

%% ---- derived atoms: combine alternative derivations + explicit weight via ⊕ --
%% clingo #max keeps #sup / drops #inf and #min keeps #inf / drops #sup, which is
%% exactly the ⊕ identity (max-identity #inf, min-identity #sup), so no special
%% infinity handling is needed for the combine itself.
pweight(P, X, W) :-
    oplus(max), derived_atom(X), phase_active(P, X),
    W = #max{ V,R : rule_deriv(P,R,X,V) ; V : direct_weight(P,X,V) }.
pweight(P, X, W) :-
    oplus(min), derived_atom(X), phase_active(P, X),
    W = #min{ V,R : rule_deriv(P,R,X,V) ; V : direct_weight(P,X,V) }.

%% ---- expose the two phases under their conventional names --------------------
supported_with_weight(X, W) :- pweight(support, X, W).
undefeated_weight(X, W)     :- pweight(undefeated, X, W).

%% ---- attack affordability for defense semantics (polarity-parameterized) -----
unaffordable_attack(W, B) :- affordability_polarity(strength), undefeated_weight(_, W), budget(B), B = #sup, W != #sup.
unaffordable_attack(W, B) :- affordability_polarity(strength), undefeated_weight(_, W), budget(B), B = 0,     W != #inf.
unaffordable_attack(W, B) :- affordability_polarity(strength), undefeated_weight(_, W), budget(B), B != #sup, B != 0, W < B.
unaffordable_attack(W, B) :- affordability_polarity(cost),     undefeated_weight(_, W), budget(B), B = 0,     W != #inf.
unaffordable_attack(W, B) :- affordability_polarity(cost),     undefeated_weight(_, W), budget(B), B != 0,    W > B.


otimes_annihilator(A) :- oplus_identity(A).
opposite_infinity(#inf) :- oplus_identity(#sup).
opposite_infinity(#sup) :- oplus_identity(#inf).

add_body_has_annih(P, R) :- body(R, B), pweight(P, B, A), otimes_annihilator(A).
add_body_has_opp(P, R)   :- body(R, B), pweight(P, B, O), opposite_infinity(O).

%% Annihilator wins (a ⊗ 0̄ = 0̄).
rule_deriv(P, R, X, A) :-
    rule(R), head(R, X), has_body(R), phase_triggered(P, R),
    add_body_has_annih(P, R), otimes_annihilator(A).
%% No annihilator, but the opposite infinity saturates.
rule_deriv(P, R, X, O) :-
    rule(R), head(R, X), has_body(R), phase_triggered(P, R),
    not add_body_has_annih(P, R), add_body_has_opp(P, R), opposite_infinity(O).
%% Finite case: plain integer sum (no infinities present).
rule_deriv(P, R, X, W) :-
    rule(R), head(R, X), has_body(R), phase_triggered(P, R),
    not add_body_has_annih(P, R), not add_body_has_opp(P, R),
    W = #sum{ V,B : body(R,B), pweight(P,B,V) }.


`
    },
    defaults: {
        "aba": `%% Use ABA-recovery defaults for unweighted assumptions.
%% This chooses the semiring-specific "hard to discard" value.
explicit_default_policy(aba).
`,
        "base": `%% Default weight policy selection for unweighted assumptions.
%%
%% Semiring modules provide semiring_default_weight(policy, value).
%% Callers may optionally load one explicit policy module from defaults/.
%% If none is loaded, legacy behavior is preserved.

configured_default_policy :- explicit_default_policy(_).

:- explicit_default_policy(P1), explicit_default_policy(P2), P1 != P2.

active_default_policy(P) :- explicit_default_policy(P).
active_default_policy(legacy) :- not configured_default_policy.

default_assumption_weight(W) :-
    active_default_policy(P),
    semiring_default_weight(P, W).

:- active_default_policy(P), not semiring_default_weight(P, _).
`,
        "legacy": `%% Preserve the pre-refactor default behavior for unweighted assumptions.
explicit_default_policy(legacy).
`,
        "neutral": `%% Use the semiring-specific conjunction-neutral default for unweighted assumptions.
explicit_default_policy(neutral).
`
    },
    monoid: {
        "max": `%% Max monoid family.
%% Aggregate: maximum discarded attack weight.
%% Identity on the empty set: #inf.

active_monoid(max).

%% Canonical aggregate over the discarded-attack multiset (single source of truth).
%% Consumed by constraint/ub.lp, constraint/lb.lp and optimize/{minimize,maximize}.lp.
budget_value(C) :- C = #max{ W : discarded_attack(_,_,W) }.
`,
        "min": `%% Min monoid family.
%% Aggregate: minimum discarded attack weight.
%% Identity on the empty set: #sup.

active_monoid(min).

%% Canonical aggregate over the discarded-attack multiset (single source of truth).
%% Consumed by constraint/ub.lp, constraint/lb.lp and optimize/{minimize,maximize}.lp.
budget_value(C) :- C = #min{ W : discarded_attack(_,_,W) }.
`,
        "sum": `%% Sum monoid family.
%% Aggregate: sum of discarded attack weights.
%% Identity on the empty set: 0.

active_monoid(sum).

%% Canonical aggregate over the discarded-attack multiset (single source of truth).
%% Consumed by constraint/ub.lp, constraint/lb.lp and optimize/{minimize,maximize}.lp.
budget_value(C) :- C = #sum{ W,X,Y : discarded_attack(X,Y,W) }.
`
    },
    optimize: {
        "maximize": `%% Generic maximization objective over the active monoid family.

active_optimization(maximize).

:- active_optimization(minimize).
:- not active_monoid(sum), not active_monoid(max), not active_monoid(min).
:- 2 { active_monoid(sum); active_monoid(max); active_monoid(min) }.

%% Sum: maximize the discarded multiset directly (fast path).
#maximize { W,X,Y : active_monoid(sum), discarded_attack(X,Y,W) }.

%% Max/Min: maximize budget_value/1 (the active monoid aggregate from monoid/<m>.lp).
:~ active_monoid(max), budget_value(M), M = #inf. [1@2]
:~ active_monoid(max), budget_value(M), M != #sup. [-1@1]
:~ active_monoid(max), budget_value(M), M != #sup, M != #inf. [-M@0]

:~ active_monoid(min), budget_value(M), M = #inf. [1@2]
:~ active_monoid(min), budget_value(M), M != #inf. [-1@1]
:~ active_monoid(min), budget_value(M), M != #sup, M != #inf. [-M@0]
`,
        "minimize": `%% Generic minimization objective over the active monoid family.

active_optimization(minimize).

:- active_optimization(maximize).
:- not active_monoid(sum), not active_monoid(max), not active_monoid(min).
:- 2 { active_monoid(sum); active_monoid(max); active_monoid(min) }.

%% Sum: minimize the discarded multiset directly (fast path; no single aggregate term).
#minimize { W,X,Y : active_monoid(sum), discarded_attack(X,Y,W) }.

%% Max/Min: minimize budget_value/1 (the active monoid aggregate from monoid/<m>.lp).
%% #sup/#inf are ordered above/below finite costs via separate priority levels.
:~ active_monoid(max), budget_value(M), M = #sup. [1@2]
:~ active_monoid(max), budget_value(M), M = #inf. [0@1]
:~ active_monoid(max), budget_value(M), M != #sup, M != #inf. [M@0]

:~ active_monoid(min), budget_value(M), M = #inf. [1@2]
:~ active_monoid(min), budget_value(M), M = #sup. [0@1]
:~ active_monoid(min), budget_value(M), M != #sup, M != #inf. [M@0]
`
    },
    constraint: {
        "lb": `%% Generic lower-bound budget constraint.

active_budget_mode(lb).
active_constraint(lb).

:- not active_monoid(sum), not active_monoid(max), not active_monoid(min).
:- 2 { active_monoid(sum); active_monoid(max); active_monoid(min) }.

%% budget_value/1 is the active monoid's aggregate, defined once in monoid/<m>.lp.

%% An empty discard set spends nothing; it does not "meet" a positive lower bound,
%% but it must remain FEASIBLE (the no-discard extension always exists). Without this
%% guard the max monoid breaks: #max{} over no discards = #inf < beta, which would
%% reject the no-discard extension outright. The min empty aggregate (#sup) already
%% passes a lower bound, so guarding only changes the otherwise-broken max+lb case.
some_discard :- discarded_attack(_,_,_).
:- budget_value(C), C < B, budget(B), some_discard.
:- discarded_attack(_,_,#sup).
`,
        "no_discard": `%% No Discarding Constraint
%% =========================
%%
%% Enforces classical ABA by forcing the discard set to be empty
%%
%% Use with: Any semantic file for pure ABA/ASPforABA compatibility
%%
%% Semantics: direct no-discard profile, independent of monoid loading
%%
%% Usage:
%%   clingo -n 0 WABA/core/base.lp WABA/semiring/godel.lp \\
%%          WABA/constraint/no_discard.lp WABA/filter/standard.lp \\
%%          WABA/semantics/<semantic>.lp framework.lp

%% Reject any extension that discards any attack
active_budget_mode(no_discard).
active_constraint(no_discard).
:- discarded_attack(_,_,_).
`,
        "ub": `%% Generic upper-bound budget constraint.

active_budget_mode(ub).
active_constraint(ub).

:- not active_monoid(sum), not active_monoid(max), not active_monoid(min).
:- 2 { active_monoid(sum); active_monoid(max); active_monoid(min) }.

%% budget_value/1 is the active monoid's aggregate, defined once in monoid/<m>.lp.

%% An empty discard set spends nothing, so it trivially respects any upper bound.
%% Without this guard the min monoid breaks: #min{} over no discards = #sup, which
%% would spuriously exceed every finite beta and reject the (cost-free) no-discard
%% extension. The max/sum empty aggregates (#inf/0) already pass an upper
%% bound, so guarding only changes the otherwise-broken min+ub case.
some_discard :- discarded_attack(_,_,_).
:- budget_value(C), C > B, budget(B), some_discard.
:- discarded_attack(_,_,#sup).
`
    },
    filter: {
        "projection": `%% Output filtering for projection mode: show in/out and discarded attacks
#show in/1.
#show out/1.
#show discarded_attack/3.
`,
        "standard": `#show in/1.
#show out/1.
#show undec/1.
#show supported_with_weight/2.
#show attacks_successfully_with_weight/3.
#show discarded_attack/3.

% Framework structure (needed for attack derivation tracing)
#show assumption/1.
#show contrary/2.
#show head/2.
#show body/2.
`
    },
    semantics: {
        "admissible": `defeated(X) :- attacks_successfully_with_weight(_,X,_).
1{ in(X); out(X) }1 :- assumption(X).
:- in(X), defeated(X).

%% Admissibility

derived_from_undefeated(X) :- assumption(X), not defeated(X).
derived_from_undefeated(X) :- head(R,X), triggered_by_undefeated(R).
triggered_by_undefeated(R) :- rule(R), derived_from_undefeated(X) : body(R,X).
attacked_by_undefeated(X) :- contrary(X,Y), undefeated_weight(Y,W), budget(B), unaffordable_attack(W,B).
:- in(X), attacked_by_undefeated(X).
`,
        "cf": `defeated(X) :- attacks_successfully_with_weight(_,X,_).
1{ in(X); out(X) }1 :- assumption(X).
:- in(X), defeated(X).`,
        "complete": `%% Complete Semantics
%% Builds upon: Admissible

defeated(X) :- attacks_successfully_with_weight(_,X,_).
1{ in(X); out(X) }1 :- assumption(X).
:- in(X), defeated(X).

%% Admissibility

derived_from_undefeated(X) :- assumption(X), not defeated(X).
derived_from_undefeated(X) :- head(R,X), triggered_by_undefeated(R).
triggered_by_undefeated(R) :- rule(R), derived_from_undefeated(X) : body(R,X).
attacked_by_undefeated(X) :- contrary(X,Y), undefeated_weight(Y,W), budget(B), unaffordable_attack(W,B).
:- in(X), attacked_by_undefeated(X).


%% Completeness: All unattacked assumptions must be IN
%% If an assumption is not attacked by any undefeated element, it must be in the extension
:- out(X), assumption(X), not attacked_by_undefeated(X).

`,
        "grounded": `%% Grounded Semantics
%% Minimal complete extension
%%
%% Implementation: Minimize |in| subject to completeness
%% Priority @5 ensures semantic selection precedes cost optimization

%% Complete Semantics
%% Builds upon: Admissible

defeated(X) :- attacks_successfully_with_weight(_,X,_).
1{ in(X); out(X) }1 :- assumption(X).
:- in(X), defeated(X).

%% Admissibility

derived_from_undefeated(X) :- assumption(X), not defeated(X).
derived_from_undefeated(X) :- head(R,X), triggered_by_undefeated(R).
triggered_by_undefeated(R) :- rule(R), derived_from_undefeated(X) : body(R,X).
attacked_by_undefeated(X) :- contrary(X,Y), undefeated_weight(Y,W), budget(B), unaffordable_attack(W,B).
:- in(X), attacked_by_undefeated(X).


%% Completeness: All unattacked assumptions must be IN
%% If an assumption is not attacked by any undefeated element, it must be in the extension
:- out(X), assumption(X), not attacked_by_undefeated(X).



%% MAIN (@5): Minimize cardinality of extension to find grounded (minimal complete)
%% Priority @5 ensures separation from cost optimization (@1-@3)
#minimize { 1@5, X : in(X) }.

`,
        "stable": `%% Guess an extension
1{ in(X); out(X) }1 :- assumption(X).

%% Conflict-free on successful attacks
:- supported(X), in(Y), attacks_successfully_with_weight(X,Y,_).

%% Defeated-by-S (counterattacked)
defeated(Y) :- supported(Z), assumption(Y), attacks_successfully_with_weight(Z,Y,_).

%% stable
:- not defeated(X), out(X).
`,
        "subset_maximal_filter": `%% Exact subset-maximal filtering over precomputed candidate extensions.
%%
%% Expected facts:
%%   candidate(M).
%%   member(M,A).
%%
%% Output:
%%   keep(M).
%%
%% Rationale:
%%   exact subset-maximality is a set-inclusion property; it is kept separate
%%   from WABA's numeric weight optimization layer instead of being encoded with
%%   plain #maximize priority levels.

model_pair(I,J) :- candidate(I), candidate(J), I != J.

not_subset(I,J) :- model_pair(I,J), member(I,A), not member(J,A).
has_extra(J,I) :- model_pair(I,J), member(J,A), not member(I,A).

strict_subset(I,J) :-
    model_pair(I,J),
    not not_subset(I,J),
    has_extra(J,I).

dominated(I) :- strict_subset(I,J).
keep(I) :- candidate(I), not dominated(I).

#show keep/1.
`,
        "subset_minimal_filter": `%% Exact subset-minimal filtering over precomputed candidate extensions.
%%
%% Dual of subset_maximal_filter.lp. Used for grounded semantics (the grounded
%% extension is the subset-minimal complete extension).
%%
%% Expected facts:
%%   candidate(M).
%%   member(M,A).
%%
%% Output:
%%   keep(M).
%%
%% Rationale:
%%   exact subset-minimality is a set-inclusion property; it is kept separate
%%   from WABA's numeric weight optimization layer instead of being encoded with
%%   plain #minimize priority levels.

model_pair(I,J) :- candidate(I), candidate(J), I != J.

not_subset(I,J) :- model_pair(I,J), member(I,A), not member(J,A).
has_extra(J,I) :- model_pair(I,J), member(J,A), not member(I,A).

strict_subset(I,J) :-
    model_pair(I,J),
    not not_subset(I,J),
    has_extra(J,I).

%% I is dominated (not minimal) when some other candidate J is a strict subset of I.
dominated(I) :- strict_subset(J,I).
keep(I) :- candidate(I), not dominated(I).

#show keep/1.
`
    },
    examples: {
        "simple_attack": `%% Simple test framework for comparing WABA semantics with ASPARTIX
%%
%% Structure: a attacks b, c is independent
%%
%% Expected (classical ABA / AAF):
%%   Stable: {a,c}
%%   Admissible: {}, {a}, {c}, {a,c}
%%   Complete: {a,c}
%%   Grounded: {a,c}
%%   Preferred: {a,c}

assumption(a).
assumption(b).
assumption(c).

% a attacks b
contrary(b, a).

% Weights (all equal for plain ABA behavior)
weight(a, 1).
weight(b, 1).
weight(c, 1).

% Budget definition for constraint files
% Use beta=0 for plain ABA (no attack discarding)
#const beta = 0.
budget(beta).
`,
        "practical_deliberation": `%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% PRACTICAL DELIBERATION - Commonsense Default Reasoning for Daily Planning
%%
%% STORY:
%% An agent planning a Sunday routine relies on four defeasible default beliefs:
%% traffic is light on Sundays, gym opens at 7am, no rain expected, no meetings.
%% These defaults generate action plans. Unexpected events (gym_closed,
%% traffic_heavy, rain_detected, meeting_scheduled) defeat defaults, forcing
%% belief revision. We minimize total revision cost (cognitive parsimony).
%%
%% WEIGHT INTERPRETATION:
%% Weights represent cognitive revision cost (1-10, belief entrenchment).
%% Higher weights = more entrenched belief (harder to revise).
%%
%% SEMIRING: Arctic (sum/max, dual of Tropical)
%% JUSTIFICATION: Belief strength accumulates (reward-based). Stronger defaults
%% = higher cumulative value. Arctic is dual of Tropical (identity 0, not #sup).
%%
%% MONOID: Sum
%% JUSTIFICATION: Extension cost = total revision cost (sum of the disruption
%% weights of the overridden defaults). Heavier defaults cost more to revise.
%%
%% OPTIMIZATION: Minimize
%% JUSTIFICATION: Minimize total revision cost (cognitive conservatism).
%%
%% BUDGET β: Upper bound on total revision cost.
%% β = 20 means "spend at most 20 total on revisions"
%%
%% DISCARDED ATTACK INTERPRETATION:
%% Overriding a disruption = maintaining the default despite contrary evidence
%% (cost = that disruption's weight). We sum the cost of the defaults we abandon.
%%
%% USAGE:
%% clingo -n 0 --opt-mode=optN -c beta=20 \\
%%   WABA/core/base.lp \\
%%   WABA/semiring/arctic.lp \\
%%   WABA/monoid/sum.lp \\
%%   WABA/optimize/minimize.lp \\
%%   WABA/constraint/ub.lp \\
%%   WABA/filter/standard.lp \\
%%   WABA/semantics/stable.lp \\
%%   WABA/examples/practical_deliberation/practical_deliberation.lp
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Budget parameter (override via -c beta=N)
#const beta = 20.

%% ============================================================================
%% ASSUMPTIONS (Commonsense Defaults)
%% ============================================================================

assumption(assume_traffic_light).  % Default: Sunday traffic is light
assumption(assume_gym_open).       % Default: Gym open at 7am
assumption(assume_weather_good).   % Default: No rain expected
assumption(assume_no_meeting).     % Default: No Sunday meetings

%% ============================================================================
%% WEIGHTS (Belief Entrenchment - for Arctic semiring)
%% ============================================================================

%% Default belief weights (entrenchment 1-10)
weight(assume_traffic_light, 8).   % Highly entrenched: Sundays are usually quiet
weight(assume_gym_open, 7).         % Moderately entrenched: Usually open
weight(assume_weather_good, 6).     % Less entrenched: Weather variable
weight(assume_no_meeting, 9).       % Very entrenched: Rarely meet Sundays

%% Disruption weights (summed by the Sum monoid as total revision cost)
weight(gym_closed, 7).
weight(traffic_heavy, 8).
weight(rain_detected, 6).
weight(meeting_scheduled, 9).

%% Plan weights
weight(plan_early_workout, 5).
weight(plan_drive_downtown, 6).
weight(plan_outdoor_run, 5).

%% ============================================================================
%% RULES (Defaults → Plans, Disruptions Defeat Defaults)
%% ============================================================================

%% r1: Gym open default → plan early workout
head(r1, plan_early_workout).
body(r1, assume_gym_open).

%% r2: Light traffic default → plan to drive
head(r2, plan_drive_downtown).
body(r2, assume_traffic_light).

%% r3: Good weather default → plan outdoor run
head(r3, plan_outdoor_run).
body(r3, assume_weather_good).

%% r4: Gym closed observed → disruption
head(r4, gym_closed).
% No body - this is an observed fact (gym unexpectedly closed on Sundays)

%% r5: Traffic report shows heavy traffic → disruption
head(r5, traffic_heavy).
% No body - unexpected traffic due to event

%% r6: Weather update shows rain → disruption
head(r6, rain_detected).
% No body - forecast updated

%% r7: Meeting invitation received → disruption
head(r7, meeting_scheduled).
% No body - unexpected Sunday meeting

%% ============================================================================
%% CONTRARIES (Disruptions Defeat Defaults)
%% ============================================================================

contrary(assume_gym_open, gym_closed).
contrary(assume_traffic_light, traffic_heavy).
contrary(assume_weather_good, rain_detected).
contrary(assume_no_meeting, meeting_scheduled).

%% ============================================================================
%% BUDGET CONSTRAINT
%% ============================================================================

%% Budget constraint enforced by loading constraint/ub.lp
%% (total revision cost ≤ β)
`,
        "probabilistic": `%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% WEIGHTS AS PROBABILITIES — most-probable-proof (Viterbi) WABA
%%
%% Probabilities MULTIPLY along a derivation; -ln turns product into sum, so the
%% TROPICAL semiring (min,+) computes the most-probable proof (Viterbi):
%%
%%   encode:  w = round(-1000 * ln p)     (p in (0,1] -> integer w >= 0; p=1 -> 0)
%%   decode:  p = exp(-w / 1000)
%%
%%   conjunction (rule body)   : +   over body  = surprisal of the product of premises
%%   disjunction (derivations) : min            = the most probable proof
%%
%% This is the Viterbi semiring ([0,1], max, x) carried onto tropical (min,+) by the
%% order-isomorphism p |-> -ln p. (Full MARGINAL probabilities -- a sum over ALL
%% proofs -- would instead need the sum-product semiring, i.e. the ProbLog setting.)
%%
%% Probability table used below (p -> encoded weight):
%%   rain        p = 0.90  ->  105
%%   sprinkler   p = 0.70  ->  357
%%   cold_night  p = 0.50  ->  693
%%
%% SEMIRING : tropical (min,+), lower-is-better (smaller surprisal = more probable)
%% MONOID   : sum  (the dismissed attacks' surprisals add; ub budget beta bounds the
%%            JOINT probability of what you dismiss: sum <= beta  <=>  prod p >= e^-beta/1000)
%%
%% RUN (pure propagation; read supported_with_weight(X,w) and decode p = exp(-w/1000)):
%%   ./bin/waba run --framework examples/probabilistic/probabilistic.lp \\
%%        --semiring tropical --semantics stable --show standard
%%
%% RUN (budgeted: is the dry_path defence affordable? enumerate within beta):
%%   clingo -n 0 -c beta=800 core/base.lp semiring/tropical.lp monoid/sum.lp \\
%%        constraint/ub.lp filter/projection.lp semantics/stable.lp \\
%%        examples/probabilistic/probabilistic.lp
%%   The {rain,sprinkler,cold_night,dry_path} extension discards \`slippery\` at
%%   surprisal 798 (probability 0.45) and is feasible iff beta >= 798; it vanishes
%%   at beta < 798. (sum+ub bounds the JOINT probability of the dismissed attacks
%%   at >= exp(-beta/1000); under sum-min the optimiser instead prefers discarding
%%   nothing, i.e. dry_path out at cost 0.)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Probabilistic leaves (assumptions), weights = surprisals
assumption(rain).        weight(rain, 105).        % p = 0.90
assumption(sprinkler).   weight(sprinkler, 357).   % p = 0.70
assumption(cold_night).  weight(cold_night, 693).  % p = 0.50

%% grass_wet holds if it rained OR the sprinkler ran (two independent proofs)
head(r1, grass_wet).  body(r1, rain).        % grass_wet <- rain
head(r2, grass_wet).  body(r2, sprinkler).   % grass_wet <- sprinkler
%% => supported_with_weight(grass_wet, min(105,357)=105) -> p = e^-0.105 = 0.90
%%    (the most probable proof: it rained)

%% the path is slippery if the grass is wet AND the night is cold (frost)
head(r3, slippery).   body(r3, grass_wet).  body(r3, cold_night).   % slippery <- grass_wet, cold_night
%% => supported_with_weight(slippery, 105+693=798) -> p = e^-0.798 = 0.45 = 0.90 * 0.50

%% Default belief: the path is safe to walk. The (probabilistic) conclusion
%% \`slippery\` is its contrary, i.e. slippery attacks dry_path with weight 798.
assumption(dry_path).
contrary(dry_path, slippery).
%% Under sum+ub, dry_path can be accepted only by discarding the slippery attack,
%% at surprisal cost 798 (probability 0.45); beta caps that cost.
`,
        "aspforaba_journal_example": `%% Journal paper reference case from ASPforABA comparison work.
%% Expected classical results with no attack discarding:
%% - admissible: 7
%% - complete: 3
%% - stable: 2
%% - preferred: 2
%% - grounded: 1

assumption(a).
assumption(b).
assumption(c).
assumption(d).

contrary(b, x).
contrary(c, y).
contrary(d, z).

head(r1, w). body(r1, a).
head(r2, y). body(r2, b). body(r2, w).
head(r3, x). body(r3, c).
head(r4, z). body(r4, a). body(r4, b).

weight(a, 100).
weight(b, 100).
weight(c, 100).
weight(d, 100).
weight(w, 100).
weight(x, 100).
weight(y, 100).
weight(z, 100).

#const beta = 0.
budget(beta).
`,
        "scientific_theory": `%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% SCIENTIFIC THEORY CHOICE - Explanatory Power vs. Theoretical Complexity
%%
%% STORY:
%% A scientist must choose between competing theoretical hypotheses (Newtonian,
%% relativistic, quantum, auxiliary) to explain experimental data. Each theory,
%% combined with observational data, generates predictions. Theories conflict
%% when they make incompatible predictions (theoretical inconsistency). We
%% maximize explanatory power while bounding total theoretical complexity.
%%
%% WEIGHT INTERPRETATION:
%% Weights represent theoretical complexity cost (0-100). Higher weights =
%% more complex theory (harder to justify, higher cognitive burden).
%%
%% SEMIRING: Tropical (sum/min)
%% JUSTIFICATION: Explanatory power accumulates across phenomena. When a
%% theory explains multiple phenomena, the evidential support combines
%% additively (cumulative explanatory strength).
%%
%% MONOID: Sum
%% JUSTIFICATION: Extension cost = total theoretical complexity of discarded
%% inconsistencies. Each time we accept a theoretical conflict, we incur
%% complexity cost. Sum represents total complexity burden.
%%
%% OPTIMIZATION: Maximize explanatory adequacy via minimizing complexity cost
%% JUSTIFICATION: We want to maximize explanatory power. Using sum + minimize,
%% we minimize complexity cost, which is equivalent to maximizing explanatory
%% strength (simpler theories preferred, Ockham's razor).
%%
%% BUDGET β: Upper bound on total theoretical complexity.
%% β = 275 means "total complexity ≤ 275"
%%
%% DISCARDED ATTACK INTERPRETATION:
%% Overriding an inconsistency = accepting theoretical complexity (cost =
%% complexity penalty). We maintain incompatible theories by accepting the
%% complexity burden.
%%
%% USAGE:
%% clingo -n 0 --opt-mode=optN -c beta=275 \\
%%   WABA/core/base.lp \\
%%   WABA/semiring/tropical.lp \\
%%   WABA/monoid/sum.lp \\
%%   WABA/optimize/minimize.lp \\
%%   WABA/constraint/ub.lp \\
%%   WABA/filter/standard.lp \\
%%   WABA/semantics/stable.lp \\
%%   WABA/examples/scientific_theory/scientific_theory.lp
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Budget parameter (override via -c beta=N)
#const beta = 275.

%% ============================================================================
%% ASSUMPTIONS (Theoretical Hypotheses)
%% ============================================================================

assumption(assume_newtonian).         % Newtonian mechanics applies
assumption(assume_relativistic).      % Relativistic corrections needed
assumption(assume_quantum).           % Quantum effects relevant
assumption(assume_auxiliary_h1).      % Auxiliary hypothesis 1

%% ============================================================================
%% WEIGHTS (Theoretical Complexity)
%% ============================================================================

%% Theory complexity weights (0-100, higher = more complex)
weight(assume_newtonian, 30).         % Simplest theory
weight(assume_relativistic, 60).      % More complex
weight(assume_quantum, 70).           % Most complex fundamental theory
weight(assume_auxiliary_h1, 40).      % Auxiliary adds complexity

%% Inconsistency complexity weights (cost of accepting conflicts)
weight(incompatible_newtonian_quantum, 80).   % High complexity to maintain both
weight(incompatible_classical_relativistic, 65). % Moderate complexity
weight(excessive_complexity, 50).      % Too many auxiliary hypotheses

%% Prediction weights (explanatory contribution)
weight(predict_orbit_precession, 45).
weight(predict_time_dilation, 50).
weight(explain_photoelectric, 55).

%% Observational data weights
weight(observation_mercury_precession, 20).
weight(observation_gps_time_dilation, 25).
weight(observation_photoelectric_effect, 30).

%% ============================================================================
%% RULES (Theories + Observations → Predictions → Inconsistencies)
%% ============================================================================

%% r1-r3: Observational data (always holds)
head(r1, observation_mercury_precession).
head(r2, observation_gps_time_dilation).
head(r3, observation_photoelectric_effect).

%% r4: Relativistic theory + Mercury observation → predicts precession
head(r4, predict_orbit_precession).
body(r4, assume_relativistic).
body(r4, observation_mercury_precession).

%% r5: Relativistic theory + GPS observation → predicts time dilation
head(r5, predict_time_dilation).
body(r5, assume_relativistic).
body(r5, observation_gps_time_dilation).

%% r6: Quantum theory + photoelectric observation → explains effect
head(r6, explain_photoelectric).
body(r6, assume_quantum).
body(r6, observation_photoelectric_effect).

%% r7: Newtonian + Quantum theories together → incompatible (domain conflicts)
head(r7, incompatible_newtonian_quantum).
body(r7, assume_newtonian).
body(r7, assume_quantum).

%% r8: Classical (Newtonian) + Relativistic → incompatible for high velocities
head(r8, incompatible_classical_relativistic).
body(r8, assume_newtonian).
body(r8, assume_relativistic).

%% r9: Too many auxiliary hypotheses → excessive complexity
head(r9, excessive_complexity).
body(r9, assume_auxiliary_h1).
body(r9, assume_relativistic).
body(r9, assume_quantum).

%% ============================================================================
%% CONTRARIES (Theoretical Inconsistencies Defeat Hypotheses)
%% ============================================================================

contrary(assume_newtonian, incompatible_newtonian_quantum).
contrary(assume_quantum, incompatible_newtonian_quantum).
contrary(assume_newtonian, incompatible_classical_relativistic).
contrary(assume_auxiliary_h1, excessive_complexity).

%% ============================================================================
%% BUDGET CONSTRAINT
%% ============================================================================

%% Budget constraint enforced by loading constraint/ub.lp
%% (total complexity ≤ β)
`
    },
    metadata: {
        "generatedFrom": "ABA-variants/WABA",
        "semiringFamilies": [
            "godel",
            "tropical"
        ],
        "polarities": [
            "higher",
            "lower"
        ],
        "supportedSemiringKeys": [
            "arctic",
            "bottleneck_cost",
            "godel",
            "godel_low",
            "lukasiewicz",
            "tropical",
            "tropical_high"
        ],
        "defaults": [
            "aba",
            "base",
            "legacy",
            "neutral"
        ],
        "monoids": [
            "max",
            "min",
            "sum"
        ],
        "optimizations": [
            "maximize",
            "minimize"
        ],
        "objectives": [
            "max-min",
            "max-max",
            "min-min",
            "min-max",
            "sum-min",
            "sum-max"
        ],
        "budgetModes": [
            "none",
            "ub",
            "lb"
        ],
        "supportedSemantics": [
            "cf",
            "stable",
            "admissible",
            "complete",
            "grounded",
            "preferred"
        ],
        "postFilteredSemantics": [
            "grounded",
            "preferred"
        ],
        "canonicalSemiring": {
            "godel": {
                "higher": "godel",
                "lower": "bottleneck_cost"
            },
            "tropical": {
                "higher": "arctic",
                "lower": "tropical"
            }
        },
        "aliases": {
            "godel_low": {
                "family": "godel",
                "polarity": "lower"
            },
            "tropical_high": {
                "family": "tropical",
                "polarity": "higher"
            }
        },
        "supportedBudgetPairs": [
            {
                "monoid": "max",
                "budgetMode": "ub"
            },
            {
                "monoid": "min",
                "budgetMode": "lb"
            },
            {
                "monoid": "sum",
                "budgetMode": "ub"
            }
        ]
    }
};
